- kibana/README.md
- kibana/templates/deployment.yaml
- kibana/values.yaml
If server.ssl.enabled is set in Kibana (vi SERVER_SSL_ENABLED env var),
then the readinessProbe will use https to test for readiness.
Fixes #16
> Add https support to readinessProbe

- kibana/templates/_helpers.tpl
- kibana/tests/kibana_test.py
Before this setting nameOverride would result in resource names like
"kibana-overrider" which meant that Kibana instances would not be sorted
nicely with their Elasticsearch cluster. This changes it around so that
the name will become "overrider-kibana"
Closes #10
> Set fullname to start with the overridden name

- kibana/examples/security/Makefile
- kibana/examples/security/security.yml
Implements the config from https://github.com/elastic/helm-charts/pull/17#issuecomment-450467054
> Add https to the security example for Kibana

- elasticsearch/README.md
- elasticsearch/examples/5.x/Makefile
- elasticsearch/examples/5.x/test/goss.yaml
- elasticsearch/examples/5.x/values.yaml
- elasticsearch/examples/default/Makefile
- elasticsearch/examples/default/test/goss.yaml
- elasticsearch/examples/multi/Makefile
- elasticsearch/examples/multi/test/goss.yaml
- elasticsearch/examples/security/Makefile
- elasticsearch/examples/security/test/goss.yaml
- helpers/examples.mk
Closes #11 
Only thing I'm not sure about is whether or not to remove the current `helm test` pod. For the integration testing it doesn't add any value. But for cluster operators it does give them a very generic easy way to run `/_cluster/health`. Thoughts?
> Switch to goss for integration testing of the Elasticsearch examples

- elasticsearch/examples/7-alpha/Makefile
- elasticsearch/examples/7-alpha/test/goss.yaml
- helpers/matrix.yml
- kibana/examples/7-alpha/Makefile
- kibana/examples/7-alpha/values.yml
I will switch all of the Kibana examples over to goss testing in a
single separate PR.
> Add Kibana 7 example and update Elasticsearch 7 to also use goss

- helpers/terraform/Makefile
This will make sure that all resources such as pvcs are properly deleted
when destroying the testing cluster after each run.
> Use a dedicated testing namespace so it can be deleted

- helpers/matrix.yml
Version `1.10.x` is no longer available as of February 18th 2019 [1].
This is causing failures in ci [2].
[1]:
https://cloud.google.com/kubernetes-engine/docs/release-notes#february-18-2019
[2]:
https://devops-ci.elastic.co/job/elastic+helm-charts+master+cluster-creation/KUBERNETES_VERSION=1.10,label=docker&&virtual/109/console
> Remove kubernetes 1.10 from ci testing

- elasticsearch/templates/service.yaml
- elasticsearch/tests/elasticsearch_test.py
This is needed for service meshes like istio to work properly as
reported in #64.
Fixes #64
> [elasticsearch] Add transport port to headless service

- helpers/examples.mk
- helpers/matrix.yml
- helpers/terraform/Makefile
Also added some reliability improvements to reduce test flakiness
* Retry goss validate every 5 seconds for up to 30 seconds. (was occasionally failing on Kibana tests)
* Retry helm init 5 times
> Add all currently supported GKE versions

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+helm-charts+master+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+master+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+master+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+master+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+master+template-testing.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+pull-request+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+pull-request+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+pull-request+template-testing.yml
- .ci/jobs/elastic+helm-charts+pull-request.yml
Add JJBB job definitions to the repo so they can be managed here.
* Update job config to use new auto-generated `inject-passwords`
section. 
* Note that the publisher `infra-root+build@elastic.co` is now the
default, so it'll be appended to the list of existing publishers on any
jobs that have them, like the `trigger-parameterized-builds` publisher
for `elastic+helm-charts+pull-request`. If that's _not_ the behavior
that we want, let me know and I'll update it.
> [ci] add JJBB job definitions

- elasticsearch/values.yaml
When adding files to the `esConfig` property helm lint would throw warnings saying that it was not a table. It turns out that Helm assumed that the property was an array, resulting in Helm throwing the warning.
```
2019/02/11 11:55:55 warning: skipped value for esConfig: Not a table.
```
While the Kubernetes definitions turned out fine, the warning caused our CI solution to think that the deployments were failing.
By setting the default value for `esConfig` to an empty map the linter stopped complaining. To stay consistent I have also added default empty values for other properties.
> Set types of empty Elasticsearch values.yaml properties

- elasticsearch/README.md
- elasticsearch/examples/migration/Makefile
- elasticsearch/examples/migration/README.md
- elasticsearch/examples/migration/client.yml
- elasticsearch/examples/migration/data.yml
- elasticsearch/examples/migration/master.yml
Related: https://github.com/helm/charts/issues/10543
This is the first step in making it possible for users of the
helm/charts version to migrate to this chart. The other
part of this is writing up a guide to help users convert their existing
values files into something compatible with the new chart.
> Add migration guide for migrating from the community helm/charts repo

- helpers/bumper.py
- helpers/release.py
This is mainly to prevent the bumper.py script from modifying the wrong
files if it is run from a different directory.
Addresses: https://github.com/elastic/helm-charts/pull/96#discussion_r276026487
> Always run from the relative parent directory

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
it would fix https://github.com/elastic/helm-charts/issues/99 and https://github.com/elastic/helm-charts/issues/101
> remove discovery.zen.ping.unicast.hosts setting on esMajorVersion > 7

- helpers/matrix.yml
1.10 has been deprecated and it is no longer possible to create new
clusters with this version https://cloud.google.com/kubernetes-engine/docs/release-notes#deprecations
See failing build at https://devops-ci.elastic.co/job/elastic+helm-charts+master+cluster-creation/KUBERNETES_VERSION=1.10,label=docker&&virtual/52/console
```
* google_container_cluster.cluster: googleapi: Error 400: No valid versions with the prefix "1.10" found., badRequest
```
> Drop 1.10 from GKE testing suite

- elasticsearch/examples/upgrade/test/goss.yaml
I had this pull request opened at the same time as the version bump so
this one just missed out.
> Bump the version number for the new upgrade test

- elasticsearch/templates/statefulset.yaml
Rewrote #108 with reference https://github.com/elastic/helm-charts/issues/63#issuecomment-465081133
fixes #63 for all es versions!
> graceful termination handler for master nodes

- .ci/jobs/elastic+helm-charts+master+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+pull-request.yml
This is being added separately so we can already start running automated tests for https://github.com/elastic/helm-charts/pull/121
> Add CI jobs for filebeat chart

- .ci/jobs/elastic+helm-charts+master+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+pull-request.yml
This is being added to make sure that automated testing for the WIP
metricbeat chart is happening in #127
> Add CI definitions for metricbeat chart

- filebeat/README.md
Minor notes in the top-level Filebeat README calling out default behavior of the bundled Filebeat configuration file.
> Add usage notes for Filebeat

- kibana/examples/default/test/goss.yaml
- kibana/templates/service.yaml
- kibana/tests/kibana_test.py
Fixes #133
Before this it wasn't possible to change the service port to anything
other than 5601. E.g. if the `service.port` was changed to `80` then the
targetPort would also be set to 80 even though Kibana was listening on
5601.
> [kibana] Explicitly set the targetPort to the defined http port

- helpers/terraform/main.tf
Currently the master build GKE cleanup job is timing out after 10
minutes.
```
04:17:35 * google_container_cluster.cluster: Error waiting for deleting GKE cluster: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 10m0s)
```
The cluster does actually get cleaned up in the end. However it means
that the build is red and needs to be checked to see if it is really
gone or not.
https://devops-ci.elastic.co/job/elastic+helm-charts+master+cluster-cleanup/KUBERNETES_VERSION=1.12,label=docker&&virtual/4/console
> [ci] Set terraform timeouts to 30 minutes

- elasticsearch/README.md
> [elasticsearch] Add instructions for how to enable snapshots

- .github/ISSUE_TEMPLATE/bug_report.md
`helm get release` includes the users values.yaml, and the final merged values and all of the deployed resources and metadata. I end up asking for this in almost all bug report issues. This command is way better.
> Update issue template to include `helm get release` output

- elasticsearch/README.md
Over time the security example changed a bit and these instructions were
no longer valid or working.
Fixes: #166
> [elasticsearch] Update security example docs to match reality

- elasticsearch/examples/default/test/goss.yaml
- elasticsearch/examples/security/test/goss.yaml
- kibana/examples/default/test/goss.yaml
- kibana/examples/security/test/goss.yaml
This makes sure that:
1. The tests work in ipv4 and ipv6 environments
2. Testing the service endpoint makes sure that the listening address is
properly configured to allow traffic
Addresses: https://github.com/elastic/helm-charts/pull/169#pullrequestreview-252414635
> Always run tests against localhost or the service endpoint

- kibana/templates/ingress.yaml
- kibana/tests/kibana_test.py
> fix support wildcard tls host on ingress

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
Fixes: #183
This worked just fine if there was only 1 annotation being added. When
adding multiple annotations the extra whitespace was causing it to
break.
> [elasticsearch] Fix pvc annotations with multiple fields

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- filebeat/templates/daemonset.yaml
- filebeat/tests/filebeat_test.py
- kibana/templates/deployment.yaml
> change secretName field

- filebeat/tests/filebeat_test.py
$ __python3 -c "0600"__
```
File "<string>", line 1
0600
^
SyntaxError: invalid token
```
> Fix octal literal to work in both Python 2 and Python 3

- elasticsearch/tests/elasticsearch_test.py
This PR was tested and merged in after the sidecar was disabled by
default in https://github.com/elastic/helm-charts/pull/194
> [elasticsearch] Fix sidecar container resources test

- helpers/release.py
> raw_input() was removed in Python 3

- helpers/examples.mk
The current timeout of 30 seconds is sometimes just not enough time for
the metricbeat goss testing. Increasing this to 300 (5 minutes) means we
won't be getting any false positives failing the build like in #206
> [meta] Increase the retry timeout for goss

- kibana/templates/deployment.yaml
- kibana/tests/kibana_test.py
Fixes: #198
This value was documented and configurable but wasn't implemented in the
template.
> [kibana] Make imagePullPolicy actually do something

- elasticsearch/tests/elasticsearch_test.py
- helpers/terraform/Makefile
Template tests for the changes from #171
> [elasticsearch] Adding testing for security context

- CHANGELOG.md
- README.md
- elasticsearch/Chart.yaml
- elasticsearch/README.md
- filebeat/Chart.yaml
- filebeat/README.md
- helpers/bumper.py
- helpers/release.md
- kibana/Chart.yaml
- kibana/README.md
- metricbeat/Chart.yaml
- metricbeat/README.md
Intermediate release to get the metricbeat chart live along wiht some
other nice changes.
* Dropped the `--version` specifier in the readmes. This was only needed
back when we had the alpha flag because otherwise `helm install
elastic/elasticsearch` failed because the helm client ignored these versions.
> 7.2.1-0 Release

- kibana/templates/deployment.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
Fixes: #229
This is needed in situation where you need to mount a specific secret as
a file in a directory that contains other files. This was added for the
Elasticsearch chart to make it possible to mount the keystore, the same
option is needed for Kibana too as seen in in #229.
> [kibana] Add subPath support to secretMounts

- elasticsearch/templates/service.yaml
according to https://github.com/kubernetes/kubernetes/issues/58662 the `publishNotReadyAddresses: true` is not working. Instead they suggest this annotation as workaround: `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"`
> publishNotReadyAddresses not working

- helpers/release.py
This is needed for metricbeat to download the child charts
> [meta] Add dependency download to release script

- elasticsearch/templates/statefulset.yaml
Fixed indent on elasticsearch extraVolumes tpl. Was causing parsing errors.
> Fixed indent on elasticsearch extraVolumes tpl. Was causing parsing errors.

- metricbeat/examples/default/test/goss-metrics.yaml
- metricbeat/examples/default/test/goss.yaml
- metricbeat/examples/security/values.yaml
- metricbeat/templates/daemonset.yaml
- metricbeat/values.yaml
This configuration didn't work at all since the nodes localhost is not
reachable from the kubernetes pod. The test has also been fixed up to
make sure that the data coming in actually has proper fields in it. The
test was passing because the events were coming in but just with errors.
> [metricbeat] Fix default configuration for kubernetes module

- helpers/terraform/main.tf
The current version started failing a couple of days ago with some very
weird terraform crashes. The latest version is working as expected
though.
https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+cluster-creation/129/KUBERNETES_VERSION=1.12,label=docker&&virtual/console
> Bump google terraform provider to the latest

- elasticsearch/README.md
- elasticsearch/examples/config/Makefile
- elasticsearch/examples/config/README.md
- elasticsearch/examples/config/test/goss.yaml
- elasticsearch/examples/config/values.yaml
- elasticsearch/examples/config/watcher_encryption_key
- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
- helpers/matrix.yml
> [elasticsearch] Keystore integration

- helpers/matrix.yml
Support for 1.11 has been dropped by GKE and 1.14 has been added
> [meta] Add Kubernetes 1.14 and drop 1.11

- helpers/terraform/Makefile
Addresses comments from #287.
This version is only used when someone is testing out the terraform
automation locally but still useful to keep updated to a known working
version.
> [meta] Update default kubernetes version in makefile

- elasticsearch/templates/configmap.yaml
- elasticsearch/templates/service.yaml
- elasticsearch/templates/statefulset.yaml
As identified in #284 having the version in the label would cause the
service to be recreated during a chart version upgrade.
> [elasticsearch] Drop version from chart label in service

- kibana/templates/deployment.yaml
Signed-off-by: Riccardo Piccoli <riccardo.piccoli@softonic.com>
It appears that env vars used by kibana are `ELASTICSEARCH_USERNAME` and `ELASTICSEARCH_PASSWORD`, but readiness uses `ELASTIC_USERNAME` and `ELASTIC_PASSWORD`. This causes kibana to be unready, unless we also configure `ELASTIC_` vars.
> use same env variable as application

- elasticsearch/examples/security/Makefile
Fix 'Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818'
> Certificate has no subjectAltName

- metricbeat/templates/clusterrole.yaml
Metricbeat apparently needs access to events. I had to manually make this change to the clusterrole when installing the chart due to the following error:
`Performing a resource sync err kubernetes api: Failure 403 events is forbidden: User "system:serviceaccount:monitoring:metricbeat-metricbeat" cannot list resource "events" in API group "" at the cluster scope for *v1.EventList`
I haven't tried `filebeat` yet so I'm not sure this change is also required for it.
> [metricbeat] Enable events access to cluster role

- kibana/templates/deployment.yaml
If authentication wasn't configured correctly the Kibana readinessProbe
would still pass since `curl --fail` doesn't consider a redirect to be a
failure. If authentication fails Kibana would redirect you back to the
login page so this readinessProbe always passed for security clusters.
The tests are going to fail until #272 is merged and this PR has been
rebased on top of it.
> [kibana] Explicitly test for a 200 for readinessProbe

- elasticsearch/examples/6.x/Makefile
- elasticsearch/examples/config/Makefile
- elasticsearch/examples/default/Makefile
- elasticsearch/examples/oss/Makefile
- elasticsearch/examples/security/Makefile
- kibana/examples/6.x/Makefile
- kibana/examples/default/Makefile
- kibana/examples/oss/Makefile
- kibana/examples/security/Makefile
Related to https://github.com/elastic/helm-charts/pull/263#discussion_r326090218
> fix "; \" when there is no additional command in the makefiles

- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/statefulset.yaml
We would like to use the elasticsearch chart as a subchart, where the name of the resource needs to match the release name (the common structure used by many charts, like the official mariadb chart). 
This was quite easy to do by overriding the helm template for `uname` and `masterService` (replacing their content with `{{ .Release.Name }}-elasticsearch`), but the `endpoints` template also needs to be overridden, and due to the way parameters are passed the trick above doesn't work.
This change simply passes moves the specification of `.Values` to the helm template, enabling overrides to access top-level parameters like `.Release.Name`. The behavior stays unchanged. This template is also not used anywhere else.
> Make it possible to override the endpoint template.

- helpers/helm-tester/Dockerfile
> [helm-tester] migrate to python 3

- elasticsearch/templates/statefulset.yaml
This fixes a bug in the `keystore` initContainer as reported in https://github.com/elastic/helm-charts/issues/280.  The root cause was using `set -u` and the variable unset check `[ ! -z "$ELASTIC_PASSWORD" ]`.  Doing the variable check this way violates `set -u` since it is considered to be accessing the variable.  The fix is to change the unset check to `[ ! -z ${ELASTIC_PASSWORD+x} ]` as per https://stackoverflow.com/a/13864829/684893.
Note the error that the `keystore` initContainer reports without the fix:
```sh
k8s-prod$ kubectl logs test-elasticsearch-master-0 -c keystore
Created elasticsearch keystore in /usr/share/elasticsearch/config
Adding file /tmp/keystoreSecrets/aws-credentials/s3.client.default.access_key to keystore key s3.client.default.access_key
Adding file …
```
> [elasticsearch] Fix bug in keystore initContainer

- metricbeat/README.md
> [metricbeat] change min k8s version due to used apiVersions

- helpers/helm-tester/requirements.txt
- Freezing attrs to 19.1.0 fix `TypeError: attrib() got an unexpected keyword argument 'convert'` issue that we have with 19.2.0
- Also freezing other dependencies for safety
Fix #308
> [helm-tester] freeze all pip dependencies

- CHANGELOG.md
- elasticsearch/Chart.yaml
- elasticsearch/README.md
- elasticsearch/examples/default/test/goss.yaml
- elasticsearch/examples/openshift/test/goss.yaml
- elasticsearch/examples/oss/test/goss.yaml
- elasticsearch/examples/upgrade/test/goss.yaml
- elasticsearch/values.yaml
- filebeat/Chart.yaml
- filebeat/README.md
- filebeat/examples/default/test/goss.yaml
- filebeat/examples/oss/test/goss.yaml
- filebeat/examples/security/test/goss.yaml
- filebeat/values.yaml
- helpers/bumper.py
- helpers/examples.mk
- kibana/Chart.yaml
- kibana/README.md
- kibana/examples/default/test/goss.yaml
- kibana/values.yaml
- metricbeat/Chart.yaml
- metricbeat/README.md
- metricbeat/examples/default/test/goss-metrics.yaml
- metricbeat/examples/default/test/goss.yaml
- metricbeat/examples/oss/test/goss-metrics.yaml
- metricbeat/examples/oss/test/goss.yaml
- metricbeat/examples/security/test/goss-metrics.yaml
- metricbeat/examples/security/test/goss.yaml
- metricbeat/values.yaml
> 7.4.0 Release

- elasticsearch/templates/statefulset.yaml
This adds the same logging that occurs for all of the other keystore
items being added. Useful so that you can be sure that the bootstrap
password is properly being added when `ELASTIC_PASSWORD` is set.
> [elasticsearch] Add logging when adding password to keystore

- elasticsearch/README.md
- elasticsearch/examples/kubernetes-kind/Makefile
- elasticsearch/examples/kubernetes-kind/values.yaml
- [x ] README.md updated with any new values or changes
This PR adds support for running elastic for development purposes on Kubernetes KIND (https://github.com/kubernetes-sigs/kind) which for some reason require the directory to be created before using it for elasticsearch data. Hence the use of an initContainer.
> Adding Example for Kubernetes KIND

- filebeat/Chart.yaml
- metricbeat/Chart.yaml
- uploaded beats icons to https://helm.elastic.co/icons/beats.png
- fixed icons name in `*beats/Chart.yml`
These icons will be available on https://hub.helm.sh/charts/elastic after next release.
> Beats icons

- logstash/examples/6.x/Makefile
- logstash/examples/6.x/test/goss.yaml
- logstash/examples/default/Makefile
- logstash/examples/default/test/goss.yaml
- logstash/examples/elasticsearch/Makefile
- logstash/examples/elasticsearch/test/goss.yaml
- logstash/examples/oss/Makefile
- logstash/examples/oss/test/goss.yaml
Goss port test for `tcp:9600` is failing on GKE 1.12 due to https://github.com/aelsabbahy/goss/issues/149.
We already had this issue with Elasticsearch goss tests in https://github.com/elastic/helm-charts/commit/de1fef380e94ef6c5a0665f7c7aa4bdbb0385d0a.
> [logstash] remove goss port test

- helpers/helm-tester/Dockerfile
This remove ~500 lines of wget progress bar during [template-testing jobs](https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+master+template-testing/) and so make job logs 50% slimmer and easier to scan if we need to troubleshoot something.
> [helm-tester] make docker image build less verbose

- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
- add master branch install procedure
- remove logstash from helm repo procedure (not released yet)
- fix https://github.com/elastic/helm-charts/issues/353
> update install doc

- .github/ISSUE_TEMPLATE/bug_report.md
> add security notice to github issue template

- metricbeat/requirements.lock
- metricbeat/requirements.yaml
```
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-4.1.0, py-1.8.0, pluggy-0.13.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app/metricbeat, inifile:
collecting ... collected 15 items
tests/metricbeat_test.py::test_defaults PASSED
tests/metricbeat_test.py::test_adding_envs PASSED
tests/metricbeat_test.py::test_adding_image_pull_secrets PASSED
tests/metricbeat_test.py::test_adding_tolerations PASSED
tests/metricbeat_test.py::test_override_the_default_update_strategy PASSED
tests/metricbeat_test.py::test_setting_a_custom_service_account PASSED
tests/metricbeat_test.py::test_self_managing_rbac_resources PASSED
tests/metricbeat_test.py::test_setting_pod_security_context PASSED …
```
> bump metricbeat to latest chart and app version

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
The behaviour of the `/` endpoint changed[0] between 6.x and 7.x, whereby
previously it would return a HTTP `503` response when the cluster was
blocked, it now returns a HTTP `200` response even if there are no masters
available.
This change updates the behaviour of the `readinessProbe` command during
normal running to verify that the local node is responding and that there
are master nodes available. [1]
The desired behaviour here is that if the data nodes are unable to talk to
their master nodes for whatever reason, then the data nodes will become
`Unready` and therefore be removed from the Service load-balancer until
the master nodes are available again.
Refs:
[0] https://github.com/elastic/elasticsearch/pull/29045
[1] https://github.com/elastic/elasticsearch/issues/34897#issuecomment-5 …
> [elasticsearch] Tweak the 'readinessProbe' command to verify that master nodes are available.

- CHANGELOG.md
- metricbeat/README.md
> [metricbeat] add notice about breaking change

- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
> [helm] make more explicit that helm 3 is not supported

- filebeat/values.yaml
This PR removes `in_cluster` config from Filebeat's `add_kubernetes_metadata` processor.
This configuration was removed by https://github.com/elastic/beats/pull/13051 and https://github.com/elastic/beats/pull/13651
cc: @exekias
> Remove in_cluster config from add_kubernetes_metadata

- .github/ISSUE_TEMPLATE/bug_report.md
The output can be quite long and long output clutters up the issue description.
Note that the empty line is necessary in order for the code to be parsed correctly (see https://github.com/dear-github/dear-github/issues/166#issuecomment-322367328 for details).
> Use details tag around code backticks for 'helm get' output in issue template

- filebeat/templates/daemonset.yaml
- filebeat/tests/filebeat_test.py
- kibana/templates/deployment.yaml
- kibana/tests/kibana_test.py
- logstash/templates/statefulset.yaml
- logstash/tests/logstash_test.py
- metricbeat/templates/daemonset.yaml
- metricbeat/tests/metricbeat_test.py
Propagate custom labels to all pods for filebeat, kibana, logstash & metricbeat
Related to #383
Fix #384
> Add custom labels to pods

- filebeat/templates/daemonset.yaml
- filebeat/values.yaml
- metricbeat/templates/daemonset.yaml
- metricbeat/templates/deployment.yaml
- metricbeat/values.yaml
Some outputs can't be tested using `filebeat test output` or `metricbeat test output` commands.
Having these commands hardcoded in `ReadinessProbe` prevent to use Filebeat / Metricbeat with outputs which haven't implemented the test command.
Fix #316 and #325
> [filebeat|metricbeat] Override probes commands

- elasticsearch/templates/statefulset.yaml
> duplicate label removed

- elasticsearch/README.md
- elasticsearch/examples/microk8s/Makefile
- elasticsearch/examples/microk8s/README.md
- elasticsearch/examples/microk8s/values.yaml
> [elasticsearch] add example for microk8s

- kibana/README.md
Add doc for plugin install recommended way.
Related to #246
> [kibana] add doc for plugin install

- .github/stale.yml
This PR add [Probot](https://probot.github.io/) configuration to manage stale issues/PR:
- Issues / PR will be marked as stale (with a `triage/stale` label) after 90 days without any activity.
- Stale issues / PR will be closed automatically after 30 days without any activity.
> [botelastic] add probot config to manage stale issues/pr

- metricbeat/examples/security/values.yaml
- metricbeat/templates/daemonset.yaml
- metricbeat/values.yaml
> update hostfs to be a CLI option instead of a config option

- elasticsearch/examples/kubernetes-kind/Makefile
- elasticsearch/examples/kubernetes-kind/README.md
- elasticsearch/examples/kubernetes-kind/values.yaml
Add workaround to fix kind mount points created from PVCs not writeable by non-root users issue.
FIx #429
> [elasticsearch]  add workaround to fix kind example

- elasticsearch/values.yaml
This post start lifecycle hook will configure templates if not using logstash/filebeat, but rather something does not support managing templates (at the time of this commit) such as fluent bit.
Will come  in handy for others to have it commented out there.
- [n/a] README.md updated with any new values or changes
- [n/a] Updated template tests in `${CHART}/tests/*.py` 
- [n/a] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`
> Add commented out example of a useful post start hook

- elasticsearch/templates/statefulset.yaml
> Fixing typo

- .ci/jobs/elastic+helm-charts+master+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+pull-request.yml
- helpers/matrix.yml
This is being added to make sure that automated testing for the WIP apm-server chart is happening in #324 (like in #128).
> [apm-server] add ci tests for apm-server chart

- requirements.txt
Updates requirements.txt same as elastic/helm-charts#309 did for helpers/helm-tester/requirements.txt
- freezing attrs to 19.1.0 fix `TypeError: attrib() got an unexpected keyword argument 'convert'` issue that we have with 19.2.0
- also freezing other dependencies for safety
> Freeze pip dependencies to make make pytest work

- .ci/jobs/elastic+helm-charts+master+template-lint-python.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml
- .ci/jobs/elastic+helm-charts+pull-request.yml
- Makefile
- apm-server/tests/apmserver_test.py
- elasticsearch/tests/elasticsearch_test.py
- filebeat/tests/filebeat_test.py
- helpers/bumper.py
- helpers/common.mk
- helpers/examples.mk
- helpers/helpers.py
- helpers/release.py
- helpers/terraform/Makefile
- kibana/tests/kibana_test.py
- logstash/tests/logstash_test.py
- metricbeat/tests/metricbeat_test.py
- requirements.txt
This PR is reformatting all python scripts using [black](https://black.readthedocs.io/en/stable/) and add black formating to CI.
Also add [phony targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) and help to Makefiles.
> [meta] format with black python scripts

- .ci/jobs/elastic+helm-charts+master+template-lint-python.yml
- .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml
[Black](https://black.readthedocs.io/en/stable/) is only compatible with Python 3
> fixup! [meta] install pip dependencies before lint-python

- .ci/jobs/elastic+helm-charts+master+template-lint-python.yml
- .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml
- helpers/common.mk
[black](https://black.readthedocs.io/en/stable/) requires python >= 3.6 which is not available on ubuntu 16.04
Fix #477
> [meta] run lint-python job on ubuntu 18.04

- logstash/values.yaml
> warn in reference to  #499

- .gitignore
- helpers/terraform/Makefile
- helpers/terraform/in-docker
Add venv to .gitignore.
Add a `make clean`.
Add checks for required vault environment variables and make `in-docker`
pass `shellcheck`.
> A few dev environment tweaks

- elasticsearch/templates/NOTES.txt
If the user copies the second command from the notes, he will get an error "Error: release: not found". This PR adds a namespace parameter to the test function.
> Add namespace parameter to the test function to NOTES.txt

- helpers/bumper.py
Add the ability to switch the namespace and override versions to bump
with environment variables.
> Version bumping script enhancements

- helpers/matrix.yml
GKE 1.13 is no more available regarding [GKE release-notes] and [elastic+helm-charts+master+cluster-creation/KUBERNETES_VERSION=1.13]
[GKE release-notes]: https://cloud.google.com/kubernetes-engine/docs/release-notes#version_updates
[elastic+helm-charts+master+cluster-creation/KUBERNETES_VERSION=1.13]: https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+master+cluster-creation/KUBERNETES_VERSION=1.13,label=docker&&virtual/457/console
> [meta] drop gke 1.13 tests

- .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+staging.yml
- helpers/bumper.py
- helpers/common.mk
- helpers/examples.mk
- helpers/terraform/Makefile
Add a multijob for performing tests with staging images based on a
BUILD_ID.
The terraform helper now can create a docker registry secret in
kubernetes.
The bumper scripts now adds an `imagePullSecrets` entry to support
pulling from the private registry, and additionally handling to ensure
goss tests work when using BUILD_ID values as a bumped version.
Allow the makefile help generator to support goals that include
numbers.
> Staging image testing

- .ci/jobs/elastic+helm-charts+staging.yml
Remove the trigger conditions for the staging job.
> Run staging test jobs on demand

- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- elasticsearch/examples/security/Makefile
- helpers/bumper.py
- helpers/terraform/Makefile
Correctly target Makefile's for docker namespace changes and tweak the
replacement pattern to be more accurate. Add a few make goals to enable
pulling of the private staging image for use within the dockerized helm
test framework.
> Support staging ES security tests

- kibana/templates/deployment.yaml
It adds the `-L` flag to `curl` to allow redirections.
It fixes the readinessProbe for kibana 8.0.0-SNAPSHOT version.
Closes #548
> fix: allow redirection on the readinessProbe

- elasticsearch/templates/NOTES.txt
* remove wrong `--namespace` argument
* add `--cleanup` to clean test pod
```shell
$ helm upgrade --wait --timeout=900 --install --values values.yaml helm-es-docker-for-mac ../../
Release "helm-es-docker-for-mac" does not exist. Installing it now.
NAME:   helm-es-docker-for-mac
LAST DEPLOYED: Mon Apr  6 15:57:23 2020
NAMESPACE: default
STATUS: DEPLOYED
...
NOTES:
1. Watch all cluster members come up.
$ kubectl get pods --namespace=default -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
$ helm test helm-es-docker-for-mac --namespace=default
$ helm test helm-es-docker-for-mac --namespace=default
Error: unknown flag: --namespace
```
> [elasticsearch] fix helm test command

- .gitignore
- metricbeat/examples/6.x/test/goss.yaml
- metricbeat/examples/default/test/goss.yaml
- metricbeat/examples/oss/test/goss.yaml
- metricbeat/examples/security/test/goss.yaml
- metricbeat/examples/security/values.yaml
- metricbeat/templates/daemonset.yaml
- metricbeat/tests/metricbeat_test.py
- metricbeat/values.yaml
- Remove `in_cluster` config from `add_kubernetes_metadata`
- Update `clusterRoleRules` with recommended values
- Remove unused `/var/lib/docker/container` mount 
- Ignore vscode settings
Fixes #559
> Metricbeat improvements

- filebeat/examples/6.x/values.yaml
- filebeat/examples/security/values.yaml
- filebeat/templates/daemonset.yaml
- filebeat/values.yaml
- Remove `in_cluster` config from `add_kubernetes_metadata
- Use `container` input instead of `docker` input
- Use recommended values for `add_kubernetes_metadata`
Fixes #558
> Filebeat improvements

- .ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml
- .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml
The cluster names created for running tests can't contain the character
`.` which is part of the branch name.
> [jenkins] Fix Google cluster name

- .ci/jobs.t/elastic+helm-charts+{branch}.yml
For doing the integration tests some GKE clusters are created. There is
a dedicated job to clean up these clusters at the end of the tests.
This commit fixes the Jenkins configuration to make sure this upstream
job (which does not need parameter) is triggered.
> [ci] Fix triggering upstream cleanup job

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- helpers/bumper.py
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This commit updates the `bumper.py` script to handle the
workflows for updating the versions to test staging artifacts
and before a release, for example:
- update 7.7.0-SNAPSHOT to 7.7.0 before tagging a release, by running
`env BUMPER_VERSION_7="7.7.0" ./helpers/bumper.py`
- update 7.7.0-SNAPHSHOT to 7.7.0-abcdefgh for testing staging artifacts
by running:
`env BUMPER_VERSION_7="7.7.0-abcdefgh" BUMPER_USE_STAGING_IMAGES="true" ./helpers/bumper.py`
For now, this script does not handle the bump from 7.7.0 to 7.7.1-SNAPSHOT
for the next development iteration after a release. In the meantime,
this update should be done manually.
> [script] Update bumper script to handle SNAPSHOT versions

- .ci/jobs.t/elastic+helm-charts+{branch}+staging.yml
The multi-job configuration for testing staging artifacts was
referencing jobs from another branch. This commit makes sure the
configured jobs are all from the same git branch.
> [ci] Fix multijob configuration for testing staging artifacts

- elasticsearch/examples/security/Makefile
- kibana/examples/security/Makefile
Use a smaller image for generating a key used in testing.
~- [ ] Updated template tests in `${CHART}/tests/*.py`~ 
> Use busybox for key generation in testing

- elasticsearch/templates/test/test-elasticsearch-health.yaml
> [elasticsearch] Adds imagePullSecrets for test Pod

- elasticsearch/templates/test/test-elasticsearch-health.yaml
Apply the the security context from the values file to the test pod: this will allow the `helm test` pod to run without root and work with more restrictive pod security policies.
> [elasticsearch] Set securityContext for test pod

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
This PR updates readiness probe endpoint to check only `/` endpoint instead of `/_cluster/health?timeout=0s` when Elasticsearch is already running.
This revert to initial config which was changed in https://github.com/elastic/helm-charts/pull/380 with the exception that 503 HTTP code is accepted for 6.x (see https://github.com/elastic/elasticsearch/issues/8902 for more details about why 503 is OK on Elasticsearch 6.x).
Fix #533
> [elasticsearch] update readiness probe endpoint

- logstash/README.md
- logstash/values.yaml
* add warning that `http.host: 0.0.0.0` is required with default probes
* add syntax to disable or override default probes
> [logstash] update doc and values.yaml for http.host issues

- helpers/bumper.py
This PR update bumper script to also update versions found in the examples README files.
`7.0.0-alpha1` version is added to blacklist because we shouldn't update it in [Elasticsearch upgrade example README](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/upgrade/README.md).
> [meta]  bump version on examples readme

- CHANGELOG.md
This PR update CHANGELOG for 7.7.0 and 6.8.9 releases to specify charts moving to GA
> [meta] update changelog with GA mentions

- BREAKING_CHANGES.md
- metricbeat/templates/deployment.yaml
This fix metricbeat chart upgrades when `.Chart.Version` change.
Fix #621 
```
UPGRADE FAILED
Error: Deployment.apps "metricbeat-metricbeat-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"metricbeat-metricbeat-metrics", "chart":"metricbeat-7.7.0", "heritage":"Tiller", "release":"metricbeat"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Error: UPGRADE FAILED: Deployment.apps "metricbeat-metricbeat-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"metricbeat-metricbeat-metrics", "chart":"metricbeat-7.7.0", "heritage":"Tiller", "release":"metricbeat"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
See …
> [metricbeat] fix deployment upgrade by removing chart label from .spec.selector.matchLabels

- metricbeat/templates/daemonset.yaml
- metricbeat/templates/deployment.yaml
This tackles https://github.com/elastic/helm-charts/issues/632
Downside: leads to avoidable reloads of daemonset if deployment changes and vice versa
> [metricbeat] Fix configchecksum not being set

- kibana/templates/deployment.yaml
...which are just copied from Elasticsearch helmchart.
Resolves #636.
> [kibana] String/YAML conditions for `.Values.{extraContainers,extraInitContainers}`

- BREAKING_CHANGES.md
- elasticsearch/templates/statefulset.yaml
The `readinessProbe` was updated in #586, however this appears to have
introduced a bug which can cause the pod to report as ready before it
actually is, due to a lack of quoting around the URL query params,
combined with the use of '&'.
This commit reworks the `readinessProbe` to correctly quote things.
Reintroduced the `http` function, and added support for passing `args`
in addition to the `path`.
Also borrowed the `set --` pattern from the Kibana chart.
Fixes: #631
Fixes: #625
Related PR: #626
> [elasticsearch] Fix issue with `readinessProbe` causing outages

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
Add ability to set the file permissions when mounting a secret
https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions
> Elasticsearch secret mountmode

- kibana/templates/_helpers.tpl
- kibana/templates/configmap.yaml
- kibana/templates/deployment.yaml
- kibana/templates/ingress.yaml
- kibana/templates/service.yaml
Common labels were moved to helpers template to have only one source of truth of common/added labels shared between all Kibana resources.
Also, this extends the capability to add a custom label and this will be common between all the resources.
This is useful in many ways because it allows querying all the Kibana resources that match a common label and be used in a whole service backup with other resources outside of its chart's responsibility.
> Add extensible label support on Kibana

- elasticsearch/templates/service.yaml
According to https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md, service selector should not contain heritage.
It would break (future) migration from helm 2 to helm 3 (during the rolling update only, there could be a downtime when only old nodes with old labels are ready but service has been updated to new selector).
> Elasticsearch: do not include heritage selector

- apm-server/templates/deployment.yaml
- apm-server/values.yaml
This commit makes probes customizable using values.
The values where already partly existing but weren't used in the deployment template.
Fixes #488
> [apm-server] allow customizing probes

- elasticsearch/examples/kubernetes-kind/Makefile
- elasticsearch/examples/kubernetes-kind/README.md
- elasticsearch/examples/kubernetes-kind/values-local-path.yaml
This PR update the [kubernetes-kind](https://kind.sigs.k8s.io/) example to use new `standard` `StorageClass` instead of the `local-path` `StorageClass` which was added as a workaround for kind < 0.7.0 in #434.
> [elasticsearch] update kind example for version >= 0.7.0

- elasticsearch/examples/openshift/values.yaml
Currently, the Openshift example does not remove `runAsUser` completely. When deploying the chart in Openshift, this results in the error:
```
unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000630000, 1000639999]]
```
To verify without Openshift, you see that
```
$ helm template -f elasticsearch/examples/openshift/values.yaml elasticsearch elasticsearch/ | grep runAsUser
```
sets the UID, which is not allowed by the default Openshift security context.
This pull request fixes the example so that runAsUser is not set at all.
> podSecurityContext.runAsUser needs to be nulled as well for Openshift

- helpers/terraform/main.tf
This PR remove Stackdriver logging and monitoring from the GKE clusters created by CI tests.
> [meta] disable stackdriver for gke test clusters

- README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- metricbeat/README.md
This PR add back the Beta notices for 6.8 branch. Only releases >= 7.7.0 are GA and eligible to support.
> [doc] add back beta notices for 6.8

- CHANGELOG.md
- README.md
This PR remove the GA support mentions for 6.8.9 release. Only releases >= 7.7.0 are GA and eligible to support.
> [doc] fix ga support mentions for 6.8.9

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
Elasticsearch: set PVC labels through setting all StatefulSet labels to its volumeClaimTemplate.
Allows to track created PVCs (example: delete all PVCs from this recently deleted Release).
> Elasticsearch: set PVC labels through setting all StatefulSet labels to its volumeClaimTemplate

- README.md
As mentioned in https://github.com/elastic/helm-charts/issues/688, the docs for the `master` branch provide documentation and examples for the "latest" version.
So if users are trying to install a 6.x ES cluster, the examples may not work.
This PR adds the "latest" release versions to the Charts table, and updates the docs to better call out the preference to match the chart version to the product version.
> [docs] Improve visibility of 6.8 and 7.x releases

- helpers/helpers.py
If the `--namespace` flag isn't provided to Helm, then it will use whatever the local configured namespace is, which could be different.
This can lead to tests failing that expect the `.Release.Namespace` to resolve to `default`
> [testing] Ensure that the 'namespace' is specified in Helm command

- helpers/matrix.yml
Spotted that the `apm-server` chart isn't being tested by PR suite.
So add it to the `CHART` matrix.
> [apm-server] Add to test matrix

- filebeat/README.md
This commit document the workaround to work with Filebeat output which don't support testing.
This is required as the default readiness probe use `filebeat test output` command.
Fixes #694
> [filebeat] document probe workaround for kafka output

- elasticsearch/templates/_helpers.tpl
- elasticsearch/tests/elasticsearch_test.py
This addressing an issue where nodes are unable to locate the masters when `fullnameOverride` is used, due to the `cluster.initial_master_nodes` having the wrong name of the nodes.
> [elasticsearch] _helpers.tpl - elasticsearch.endpoints to use elasticsearch.uname

- logstash/examples/default/test/goss.yaml
- logstash/examples/elasticsearch/test/goss.yaml
- logstash/examples/oss/test/goss.yaml
- logstash/examples/security/test/goss.yaml
This commit remove expected Logstash host and name in Logstash tests with 6.x.
When using a headless service (4a6067e), Logstash 6.x use the full name of the service related to the namespace (ie: `helm-logstash-default-logstash-0.helm-logstash-oss-logstash-headless.helm-charts-testing.svc.cluster.local`). Keeping this test would require a hard coupling between the test and the namespace where it is running.
> [logstash] remove expected logstash host and name assertion

- logstash/templates/statefulset.yaml
- logstash/tests/logstash_test.py
> [logstash] Restart the logstash pod when the secrets have changed

- kibana/templates/service.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
> [Kibana] Add loadbalancerIP to service spec in kibana

- .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+staging.yml
We currently have staging jobs for every branch (6.8, 7.8, 7.x & master). However, we should only test staging from the minor release branches (ie: 6.8 & 7.8). In addition, staging jobs are only triggered manually after a BC, so staging job for a specific branch should rarely have more than 10 builds. This commit will rationalize and help having a cleaner Helm charts Jenkins view by using the same staging jobs for every branches. 
Note that staging jobs templates should be removed from the other branches.
> [meta] use same staging job for all branches

- .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+staging.yml
This commit remove the `BRANCH` CI job parameter introduced in 47a45cf because there is already a
`branch_specifier` parameter existing in [.ci/jobs/defaults.yml](https://github.com/elastic/helm-charts/blob/8f2025f82adc9598597a8790e767f46d40e782c1/.ci/jobs/defaults.yml).
> [meta] use branch_specifier param instead of BRANCH

- .ci/jobs/elastic+helm-charts+staging.yml
This fixes a typo introduced in f6d49eb which change job type from
multijob to freestyle.
> [meta] fix staging job

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+staging.yml
This PR add Slack notifications to Elastic Release team Slack channel for [elastic+helm-charts+master](https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+master/) and [elastic+helm-charts+staging](https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+staging/) test jobs.
> [meta] add slack notifications to CI jobs

- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+staging.yml
This PR is a follow up of https://github.com/elastic/helm-charts/pull/718 to add the Slack token to CI jobs configuration
> [meta] add slack token to ci jobs

- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
`test_initial_master_nodes_when_using_full_name_override` has been added in af288a9 but is not valid with 6.x version.
This commit remove from 6.8 branch the test and `elasticsearch.endpoints` template which are only used with 7.x version.
Fixes [elastic+helm-charts+6.8+template-testing](https://devops-ci.elastic.co/job/elastic+helm-charts+6.8+template-testing/130/CHART=elasticsearch,label=docker&&virtual) job.
> [elasticsearch] remove initial_master_nodes test

- .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
This commit allow concurrency for staging jobs.
The upstream matrix job does already have concurrency enabled but not the downstream jobs.
This is required so we can test staging for multiple releases in // (example when we have a 6.x and 7.x release planned for the same day).
> [meta] allow concurrency for staging jobs

- .ci/jobs/elastic+helm-charts+master.yml
- .ci/jobs/elastic+helm-charts+staging.yml
This commit adds a new auth-token-credential-id entry in addition of auth-token-id for slack token.
This is due to a bug in JJB which requires having both entries to prevent having an empty authTokenCredentialId in job config.xml (https://storyboard.openstack.org/#!/story/2007953).
> [meta] add auth-token-credential-id entry for slack

- BREAKING_CHANGES.md
- CHANGELOG.md
- README.md
- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This PR update the changelog following #753 & #754
> [meta] update changelog for 7.8.1 and 6.8.11 releases

- README.md
- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This PR add Helm 3 support in preview as the main blockers were fixed in previous PR.
Note that adding automated tests with Helm 3 is still required to add full Helm 3 support.
This PR should be backported to `6.8`, `7.x` and `7.9` branches.
> [meta] add helm 3 beta support

- helpers/matrix.yml
This PR fix CI builds failing because GKE 1.14 is no more available in GCP:
```
08:46:14 Error: Error applying plan:
08:46:14 
08:46:14 1 error(s) occurred:
08:46:14 
08:46:14 * google_container_cluster.cluster: 1 error(s) occurred:
08:46:14 
08:46:14 * google_container_cluster.cluster: googleapi: Error 400: No valid versions with the prefix "1.14" found., badRequest
08:46:14 
08:46:14 Terraform does not automatically rollback in the face of errors.
08:46:14 Instead, your Terraform state file has been partially updated with
08:46:14 any resources that successfully completed. Please address the error
08:46:14 above and apply again to incrementally change your infrastructure.
```
https://devops-ci.elastic.co/job/elastic+helm-charts+6.8+cluster-creation/KUBERNETES_VERSION=1.14,label=docker&&v …
> [meta] drop gke 1.14 tests

- filebeat/README.md
> Fix typo in FAQ

- elasticsearch/examples/security/Makefile
Purge is missing the "elastic-certificate-crt" secret deletion.
> Missing deletion of "elastic-certificate-crt"

- apm-server/values.yaml
- [] README.md updated with any new values or changes
- [] Updated template tests in `${CHART}/tests/*.py` 
- [] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`
> Remove duplicate "initialDelaySeconds" field

- apm-server/templates/deployment.yaml
Why
----
- In the current Helm chart for `apm-server`, serviceAccount for the
Deployment is only set when `serviceAccount` is set in `values.yaml`.
However, it is wrong. `serviceAccount` should always be set because even
when no `serviceAccount` is set in `values.yaml`, a managed one is still
created.
What
----
- Always set `serviceAccount` for apm-server Deployment to the template
apm.serviceAccount defined in `_helpers.tpl`
> Fix serviceAccount for APM server

- BREAKING_CHANGES.md
- CHANGELOG.md
- add missing changes for 7.9.0 / 6.8.12 release about Helm 3 beta support
- add more details about an issue related to Logstash breaking change in 7.8.1 / 6.8.11
Related to #766 and #759
> [meta] Update changelog for 7.8.1 / 7.9.0 / 6.8.11 / 6.8.12 releases

- elasticsearch/templates/statefulset.yaml
The new parameter `enableServiceLinks` added in https://github.com/elastic/helm-charts/pull/542 is only rendered with kubernetes >1.13. However the notation for the parameter to `semverCompare` requires a `-0` suffix to also take into account versions like `v1.15.12-gke.6.12`. Because of that, the `enableServiceLinks` parameter currently nothing on GKE. 
Note that the `helm template` and `helm install` will generate different values for `.Capabilities.KubeVersion.GitVersion`, something I was previously not aware of.
> Include pre-releases in the semver range.

- elasticsearch/README.md
Kubernetes doesn't accept `_` characters in resources names.
This commit fix the secrets names in the examples we provide by
replacing `_` by `-`which Kubernetes is accepting.
Source: https://github.com/helm/helm/issues/6477
Fixes #747
> [elasticsearch] fix secrets names in examples

- elasticsearch/templates/statefulset.yaml
- kibana/templates/deployment.yaml
This PR disable nss dentry cache for Elasticsearch and Kibana
readinessProbe.
On affected system (nss < 3.52), the curl commands used by
readinessProbe are filling dentry cache which is observed in some
cases to be never reclaimed.
Elasticsearch and Kibana Docker images are based on CentOS 7 which
is using nss-3.44.0-7.el7_7.x86_64 and are affected by this bug.
This PR disable nss dentry cache in readinessProbe as a
workaround.
Related to https://github.com/elastic/cloud-on-k8s/pull/1716
> [elasticsearch][kibana] disable nss dentry cache

- kibana/templates/configmap.yaml
- logstash/templates/configmap-config.yaml
- logstash/templates/configmap-pipeline.yaml
> support tpl in logstashConfig, logstashPipeline and kibanaConfig

- metricbeat/README.md
- metricbeat/templates/daemonset.yaml
- metricbeat/templates/deployment.yaml
- metricbeat/tests/metricbeat_test.py
- metricbeat/values.yaml
Closes #812
Turned out, initially labeling was completely implemented for DaemonSet (both daemon-set and pod labels), but only partially for Deployment (only pod-level labels). I decided to make these properties to be consistent for both object types, while still keeping to the design we agreed in the linked issue
> [metricbeat] support deployment/daemonset specific metrics

- filebeat/README.md
- filebeat/templates/daemonset.yaml
- filebeat/values.yaml
Signed-off-by: Oron Gola <oron.gola@perception-point.io>
> [filebeat] introduce dnsConfig values for the containers

- logstash/templates/service-headless.yaml
- logstash/tests/logstash_test.py
This commit fix an issue introduced in 8ed75a9 where helm
install/upgrade is failing if a NodePort service is defined.
Logstash headless service used to manage Statefulset does not anymore include
`.Values.service.ports` and include only Logstash httpPort.
This is done because headless service `ports` doesn't accept `nodePort`
values that can be included in `.Values.service.ports` when adding a
NodePort service.
Fix https://github.com/elastic/helm-charts/issues/807
> [logstash] use only httpPort in headless service

- metricbeat/templates/configmap.yaml
- metricbeat/tests/metricbeat_test.py
If for daemonset/deployment is not enabled, dont generate useless config YAML.
> [Metricbeat] Dont generate config if not enabled

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This PR simplifies the release process by making the charts README more generic - similar fix was done [after the `7.9.2` release ](https://github.com/elastic/helm-charts/pull/831/files)
> [all] Simplify doc in 6.8 branch

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
Reword warning statements in chart readme to streamline the release process - related PR : https://github.com/elastic/helm-charts/pull/858
> [all] Simplify doc in 7.9 branch

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
Reword warning statements in chart readme to streamline the release process - related PR : #858, #859
> [all] Simplify doc in 7.x branch

- CHANGELOG.md
- README.md
* 6.8.13 as default version.
| [#858](https://github.com/elastic/helm-charts/pull/858) | [@nkammah](https://github.com/nkammah) | [all] Simplify doc in 6.8 branch  |
| [#767](https://github.com/elastic/helm-charts/pull/767) | [@ebuildy](https://github.com/ebuildy) | [Metricbeat] Dont generate config if not enabled  |
| [#793](https://github.com/elastic/helm-charts/pull/793) | [@jnbelo](https://github.com/jnbelo) | Added ingress support to the logstash chart  |
| [#839](https://github.com/elastic/helm-charts/pull/839) | [@jmlrt](https://github.com/jmlrt) | [logstash] use only httpPort in headless service  |
| [#659](https://github.com/elastic/helm-charts/pull/659) | [@orong-pp](https://github.com/orong-pp) | [filebeat] introduce dnsConfig values …
> 6.8.13 release changelog

- CHANGELOG.md
- README.md
* 7.9.3 as default version.
| [#859](https://github.com/elastic/helm-charts/pull/859) | [@nkammah](https://github.com/nkammah) | [all] Simplify doc in 7.9 branch  |
| [#767](https://github.com/elastic/helm-charts/pull/767) | [@ebuildy](https://github.com/ebuildy) | [Metricbeat] Dont generate config if not enabled  |
| [#793](https://github.com/elastic/helm-charts/pull/793) | [@jnbelo](https://github.com/jnbelo) | fixup! Added ingress support to the logstash chart  |
| [#793](https://github.com/elastic/helm-charts/pull/793) | [@jnbelo](https://github.com/jnbelo) | Added ingress support to the logstash chart  |
| [#839](https://github.com/elastic/helm-charts/pull/839) | [@jmlrt](https://github.com/jmlrt) | [logstash] use only httpPort in headless …
> 7.9.3 release changelog

- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- metricbeat/README.md
> Remove beta warnings 6.8

- elasticsearch/examples/multi/Makefile
- elasticsearch/examples/multi/README.md
- elasticsearch/examples/multi/client.yml
- elasticsearch/examples/multi/master.yml
- elasticsearch/examples/multi/test/goss.yaml
- elasticsearch/values.yaml
This commit add a coordinator node group to elasticsearch multi test.
This also add ml and remote_cluster_client roles to default values.
Related to #832
> [elasticsearch] add coordinator node to multi test

- BREAKING_CHANGES.md
Related to #865, #861 and #803
> [meta] update breaking changes file after 7.9.3/6.8.13 releases

- elasticsearch/examples/multi/client.yml
- elasticsearch/examples/multi/data.yml
- elasticsearch/examples/multi/master.yml
- elasticsearch/values.yaml
This commit fix a bug introduced in 702ca8f where elasticsearch 6.8
start is failing because ml and remote_cluster_client node roles
are unavailable in 6.8 versions.
Related to #854
> [elasticsearch] remove roles unavailable on 6.8

- metricbeat/requirements.lock
This commit update metricbeat chart dependencies to get
kube-state-metrics subchart from the newly relocated stable repo url
(https://charts.helm.sh/stable).
This is required because the legacy stable repo url will not work
anymore starting November 13th.
More details in https://helm.sh/blog/new-location-stable-incubator-charts/
> [metricbeat] use relocated stable repo for kube-state-metrics

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
The development warning comment will help with the automation. 
I will backport the PR against `6.8`, _main branch_, `7.x` once this one is reviewed and merged.
> Add warning comment placeholder (7.9 branch)

- apm-server/templates/clusterrole.yaml
- apm-server/templates/clusterrolebinding.yaml
- filebeat/templates/clusterrole.yaml
- filebeat/templates/clusterrolebinding.yaml
- metricbeat/templates/clusterrole.yaml
- metricbeat/templates/clusterrolebinding.yaml
This commit updates Kubernetes [rbac.authorization.k8s.io][0] api from
v1beta1 in apm-server, filebeat and metricbeat charts.
- `rbac.authorization.k8s.io/v1` has been released in Kubernetes 1.8
- `rbac.authorization.k8s.io/v1beta1` is being deprecated in Kubernetes
1.17 and will be fully removed in 1.22
In addition, this is required for Helm 3 support to make `helm lint
--strict` happy.
Related to #401 
[0]: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
> [meta] update rbac.authorization.k8s.io api

- apm-server/examples/default/Makefile
- apm-server/examples/oss/Makefile
- apm-server/examples/security/Makefile
- elasticsearch/examples/config/Makefile
- elasticsearch/examples/default/Makefile
- elasticsearch/examples/docker-for-mac/Makefile
- elasticsearch/examples/kubernetes-kind/Makefile
- elasticsearch/examples/microk8s/Makefile
- elasticsearch/examples/migration/Makefile
- elasticsearch/examples/minikube/Makefile
- elasticsearch/examples/multi/Makefile
- elasticsearch/examples/openshift/Makefile
- elasticsearch/examples/oss/Makefile
- elasticsearch/examples/security/Makefile
- filebeat/examples/default/Makefile
- filebeat/examples/oss/Makefile
- filebeat/examples/security/Makefile
- kibana/examples/default/Makefile
- kibana/examples/openshift/Makefile
- kibana/examples/oss/Makefile
- kibana/examples/security/Makefile
- logstash/examples/default/Makefile
- logstash/examples/elasticsearch/Makefile
- logstash/examples/oss/Makefile
- logstash/examples/security/Makefile
- metricbeat/examples/default/Makefile
- metricbeat/examples/oss/Makefile
- metricbeat/examples/security/Makefile
This commit increase the timeout for helm upgrade commands examples to
avoid timeout error when deploying all example releases in // in helm
test gke cluster.
> [meta] increase helm timeout

- README.md
This commit add a link to ECK chart and documentation.
Fix #829
> [meta] add link to eck chart doc

- elasticsearch/templates/test/test-elasticsearch-health.yaml
This commit update Elasticsearch chart test hook annotations for Helm 3
and add a new annotation to automate test pod deletion when test is
successful.
Related to https://github.com/elastic/helm-charts/issues/401#issuecomment-729555952
> [elasticsearch] update test hook annotations

- elasticsearch/values.yaml
> [elasticsearch] Fix spelling

- apm-server/README.md
- apm-server/templates/_helpers.tpl
- apm-server/templates/hpa.yaml
- apm-server/templates/ingress.yaml
- elasticsearch/README.md
- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/ingress.yaml
- elasticsearch/templates/statefulset.yaml
- filebeat/README.md
- kibana/README.md
- kibana/templates/_helpers.tpl
- kibana/templates/ingress.yaml
- logstash/README.md
- logstash/templates/_helpers.tpl
- logstash/templates/ingress.yaml
- logstash/templates/statefulset.yaml
- metricbeat/README.md
- [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
> [7.x] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)

- apm-server/README.md
- apm-server/templates/_helpers.tpl
- apm-server/templates/hpa.yaml
- apm-server/templates/ingress.yaml
- elasticsearch/README.md
- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/ingress.yaml
- elasticsearch/templates/statefulset.yaml
- filebeat/README.md
- kibana/README.md
- kibana/templates/_helpers.tpl
- kibana/templates/ingress.yaml
- logstash/README.md
- logstash/templates/_helpers.tpl
- logstash/templates/ingress.yaml
- logstash/templates/statefulset.yaml
- metricbeat/README.md
- [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
> [7.10] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)

- apm-server/README.md
- apm-server/templates/_helpers.tpl
- apm-server/templates/hpa.yaml
- apm-server/templates/ingress.yaml
- elasticsearch/README.md
- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/ingress.yaml
- elasticsearch/templates/statefulset.yaml
- filebeat/README.md
- kibana/README.md
- kibana/templates/_helpers.tpl
- kibana/templates/ingress.yaml
- logstash/README.md
- logstash/templates/_helpers.tpl
- logstash/templates/ingress.yaml
- logstash/templates/statefulset.yaml
- metricbeat/README.md
- [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
> [6.8] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)

- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This commit update charts readme to remove the version from the dev
install section title. This is required to simplify bumping automation
and avoid having to manage toc update.
This was done in 7.9 branch in #831
Also remove an unused link
> [meta] remove version from dev install section title

- BREAKING_CHANGES.md
- CHANGELOG.md
- README.md
* 7.10.0 as default version.
| [#927](https://github.com/elastic/helm-charts/pull/927) | [@jmlrt](https://github.com/jmlrt) | [meta] Remove version from dev install section title  |
| [#922](https://github.com/elastic/helm-charts/pull/922) | [@jmlrt](https://github.com/jmlrt) | [meta] Remove support for k8s <1.14 & helm <2.17.0 (#916) [7.10]  |
| [#919](https://github.com/elastic/helm-charts/pull/919) | [@jmlrt](https://github.com/jmlrt) | [meta] Upgrade test (#907) [7.10]  |
| [#914](https://github.com/elastic/helm-charts/pull/914) | [@jmlrt](https://github.com/jmlrt) | [meta] Initiate 7.10 branch  |
| [#897](https://github.com/elastic/helm-charts/pull/897) | [@cospeedster](https://github.com/cospeedster) | [elasticsearch] Fix spelling  |
| …
> 7.10.0 release changelog

- logstash/templates/serviceaccount.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
> [logstash] add rbac custom annotations

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- ES Statefulset empty initContainers fix (#795)
> [7.x] ES Statefulset empty initContainers fix (#795)

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- ES Statefulset empty initContainers fix (#795)
> [7.10] ES Statefulset empty initContainers fix (#795)

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- ES Statefulset empty initContainers fix (#795)
> [6.8] ES Statefulset empty initContainers fix (#795)

- logstash/templates/serviceaccount.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] add rbac custom annotations (#764)
> [7.x] [logstash] add rbac custom annotations (#764)

- logstash/templates/serviceaccount.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] add rbac custom annotations (#764)
> [7.10] [logstash] add rbac custom annotations (#764)

- logstash/templates/serviceaccount.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] add rbac custom annotations (#764)
> [6.8] [logstash] add rbac custom annotations (#764)

- helpers/matrix.yml
- metricbeat/examples/upgrade/Makefile
This commit enable Metricbeat upgrade test which where disable before
7.10.0 release because Metricbeat 7.10.0 introduce breaking change
preventing upgrade from previous version.
Version post 7.10.0 will now be tested for upgrade from 7.10.0.
> [meta] enable metricbeat upgrade test

- helpers/matrix.yml
- metricbeat/examples/upgrade/Makefile
- [meta] enable metricbeat upgrade test (#940)
> [7.10] [meta] enable metricbeat upgrade test (#940)

- helpers/matrix.yml
- metricbeat/examples/upgrade/Makefile
- [meta] enable metricbeat upgrade test (#940)
> [7.x] [meta] enable metricbeat upgrade test (#940)

- kibana/templates/service.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
- [kibana] add service.httpPortName config in chart (#843)
> [6.8] [kibana] add service.httpPortName config in chart (#843)

- kibana/templates/service.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
- [kibana] add service.httpPortName config in chart (#843)
> [7.10] [kibana] add service.httpPortName config in chart (#843)

- kibana/templates/service.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
- [kibana] add service.httpPortName config in chart (#843)
> [7.x] [kibana] add service.httpPortName config in chart (#843)

- CHANGELOG.md
- README.md
* 7.10.1 as default version.
| [#958](https://github.com/elastic/helm-charts/pull/958) | [@jmlrt](https://github.com/jmlrt) | [7.10] [kibana] add service.httpPortName config in chart (#843)  |
| [#955](https://github.com/elastic/helm-charts/pull/955) | [@jmlrt](https://github.com/jmlrt) | [7.10] [apm-server] Add missing fields to HPA (#782)  |
| [#950](https://github.com/elastic/helm-charts/pull/950) | [@jmlrt](https://github.com/jmlrt) | [7.10] [meta] enable metricbeat upgrade test (#940)  |
| [#945](https://github.com/elastic/helm-charts/pull/945) | [@jmlrt](https://github.com/jmlrt) | [7.10] [logstash] add rbac custom annotations (#764)  |
| [#942](https://github.com/elastic/helm-charts/pull/942) | [@jmlrt](https://github.com/jmlrt) | [7.10] …
> 7.10.1 release changelog

- .backportrc.json
- [meta] add config for backport (#971)
> [6.8] [meta] add config for backport (#971)

- .backportrc.json
- [meta] add config for backport (#971)
> [7.10] [meta] add config for backport (#971)

- .backportrc.json
- [meta] add config for backport (#971)
> [7.x] [meta] add config for backport (#971)

- elasticsearch/values.yaml
When adding custom keystore via `keystore:` for _values.yml_, the initContainer wants to create an emptyDir-based volume as seen [here](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L135).
If you have `podSecurityPolicy.create: true` set at the same time, the current policy does not permit the use of _emptyDir_.
In such a case deployment is then failing:
```
create Pod elasticsearch-master-2 in StatefulSet elasticsearch-master failed error: pods "elasticsearch-master-2" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[4]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used
```
> elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type

- elasticsearch/values.yaml
- elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
> [6.8] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)

- elasticsearch/values.yaml
- elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
> [7.10] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)

- elasticsearch/values.yaml
- elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
> [7.x] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)

- apm-server/README.md
- apm-server/templates/deployment.yaml
- apm-server/tests/apmserver_test.py
- apm-server/values.yaml
- elasticsearch/README.md
- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
- filebeat/README.md
- filebeat/templates/daemonset.yaml
- filebeat/tests/filebeat_test.py
- filebeat/values.yaml
- kibana/README.md
- kibana/templates/deployment.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
- logstash/README.md
- logstash/templates/statefulset.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- metricbeat/README.md
- metricbeat/templates/daemonset.yaml
- metricbeat/templates/deployment.yaml
- metricbeat/tests/metricbeat_test.py
- metricbeat/values.yaml
- [all] add hostaliases (#970)
> [7.10] [all] add hostaliases (#970)

- elasticsearch/templates/ingress.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
- kibana/templates/ingress.yaml
- kibana/tests/kibana_test.py
- kibana/values.yaml
> [elasticsearch][kibana] Add flexible ingress

- filebeat/README.md
- metricbeat/README.md
> [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled.

- filebeat/README.md
- filebeat/templates/clusterrole.yaml
- filebeat/values.yaml
Co-authored-by: Julien Mailleret <8582351+jmlrt@users.noreply.github.com>
> [filebeat] Configurable ClusterRole (#978)

- filebeat/README.md
- metricbeat/README.md
Co-authored-by: ksorensen@scramsystems.com <ksorensen@scramsystems.com>
> [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled. (#997)

- elasticsearch/examples/config/test/goss.yaml
- elasticsearch/examples/config/values.yaml
This commit fix the secret name for credentials in config example
Fix #1008
> [elasticsearch] fix secrets in config example

- .backportrc.json
- README.md
- filebeat/README.md
- update backport config for 7.11 branch
- fix config headline and toc
- update support matrix
> NIT Update backport config and small doc fixes

- apm-server/README.md
- helpers/upgrade.sh
- kibana/examples/upgrade/Makefile
- kibana/examples/upgrade/test/goss.yaml
- metricbeat/examples/upgrade/test/goss-metrics.yaml
This commit update version to 7.11 in some place which were not catched in
https://github.com/elastic/helm-charts/pull/1016.
> [meta] small fixes for 7.11 branch

- helpers/terraform/Makefile
- metricbeat/examples/default/Makefile
- metricbeat/examples/oss/Makefile
- metricbeat/examples/security/Makefile
- metricbeat/examples/upgrade/Makefile
This commit move stable chart repo setup and dependency update steps to
metricbeat specific examples.
We have lot of transient issues when running configuring stable repo:
```
helm repo add stable https://charts.helm.sh/stable && \
helm dependency update && \
cd ./examples/oss && \
make
Error: looks like "https://charts.helm.sh/stable" is not a valid chart repository or cannot be reached: read tcp 172.17.0.2:37660->185.199.108.153:443: read: connection reset by peer
make: *** [integration] Error 1
```
As stable repo is only used by Metricbeat chart, by not configuring it
for other charts tests, we should limit the risk of transient issues.
> [meta] fix transient errors with stable repository

- kibana/README.md
> Fix post-lifecycle hook example

- README.md
- apm-server/README.md
- elasticsearch/README.md
- filebeat/README.md
- kibana/README.md
- logstash/README.md
- metricbeat/README.md
This commit is adding Artifact Hub badges to main and charts README
pages. Also add build status badges to charts README pages (was only
present on main README page).
> [meta] add build status and artifact hub badges

- filebeat/README.md
- filebeat/templates/daemonset.yaml
- filebeat/tests/filebeat_test.py
- filebeat/values.yaml
Unable to set a custom value for the `MaxUnavalaible` for the `rollingUpdate` filebeat's update strategy.
This option should be available especially for filbert, because there is no need to have a MaxUnavailable set to 1 when there's one filebeat pod per node. 
Add an `{{- if }}` statement to the `updateStrategy` regarding the `MaxUnavaillable` variable. If the variable is not set, the default value is et to **1** (current value set right now).
Chart version
filebeat 7.9.1
Tools versions
Helm version
Client: {Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", …
> [filebeat] variable maxUnavailable updateStrategy

- elasticsearch/examples/security/README.md
> fix: security.yaml is 404

- metricbeat/README.md
- metricbeat/requirements.yaml
Kube state metrics that were used in the metricbeat's charts were pointing towards the deprecated helm chart repository i.e "@stable" and in order to fix that we needed to point the chart towards @bitnami/kube-state-metrics which are stable and compatible with the metricbeat's deployment.
Without this small change, the charts are rendered useless since it breaks at the requirements phase.
- [x ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [✔️ ] README.md updated with any new values or changes
- [x ] Updated template tests in `${CHART}/tests/*.py` 
- [x ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`
> [metricbeat] Fixing the respository of kube-state-metrics for metricbeats

- BREAKING_CHANGES.md
- CHANGELOG.md
- README.md
* 6.8.14 as default version.
| PR                                                        | Author                                                   | Title                                                                                                                        |
|-----------------------------------------------------------|----------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| [#1040](https://github.com/elastic/helm-charts/pull/1040) | [@daniel-hutao](https://github.com/daniel-hutao)         | [elasticsearch] Fix security.yaml is 404                                                                                     |
| …
> 6.8.14 release changelog

- apm-server/templates/service.yaml
- apm-server/tests/apmserver_test.py
- apm-server/values.yaml
See https://github.com/elastic/helm-charts/issues/1031 - this PR add "service.loadBalancerIP" field. (copied from Kibana chart).
> [apm-server] Add  option loadBalancerIP to service

- apm-server/templates/service.yaml
- apm-server/tests/apmserver_test.py
- apm-server/values.yaml
- [apm-server] Add  option loadBalancerIP to service (#1075)
> [7.x] [apm-server] Add  option loadBalancerIP to service (#1075)

- elasticsearch/templates/NOTES.txt
Helm chart NOTES.txt was missing namespace in the test section:
before change:
```NAME: elasticsearch
LAST DEPLOYED: Mon Mar 15 21:24:35 2021
NAMESPACE: elk
STATUS: deployed
REVISION: 1
NOTES:
1. Watch all cluster members come up.
$ kubectl get pods --namespace=elk -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
$ helm test elasticsearch
```
after change:
```LAST DEPLOYED: Mon Mar 15 21:25:59 2021
NAMESPACE: elk
STATUS: deployed
REVISION: 1
NOTES:
1. Watch all cluster members come up.
$ kubectl get pods --namespace=elk -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
$ helm --namespace=elk test elasticsearch
```
> [elasticsearch] Add namespace to helm test command in NOTES.txt

- elasticsearch/examples/networkpolicy/Makefile
- elasticsearch/examples/networkpolicy/values.yaml
- elasticsearch/templates/networkpolicy.yaml
- elasticsearch/tests/elasticsearch_test.py
* Fix http additional rules to use with `NetworkPolicies`.
* Adds some small improvements in network policies tests:
* update example Makefile to fix commands and use similar structure to other examples Makefiles
* fix example values file extension
* use different values for http and transport network policies in python test and example values to catch regressions where same values would be used for both
Fix #1106
> [elasticsearch] fix network policies http additional rules

- .backportrc.json
This commits update sqren/backport config to handle `7.12` branch.
Also remove `7.10` and `7.11` branchs.
> [meta] update backport config for 7.12 branch

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
This commit update Elasticsearch Statefulset template to set
`ES_JAVA_OPTS` variable only when `esJavaOpts` value is defined.
This allow to benefit of JVM heap automatic sizing in Elasticsearch
7.11.
Fix #1083
> [elasticsearch] only configure ES_JAVA_OPTS when value is set

- .ci/jobs/elastic+helm-charts+master.yml
Remove the CI slack notification, these tests are too flaky and create a
lot of non-actionable noise in this notification room.
- ~[ ] Chart version *not* bumped (the versions are all bumped and released at the same time)~
- ~[ ] README.md updated with any new values or changes~
- ~[ ] Updated template tests in `${CHART}/tests/*.py`~
- ~[ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`~
> Remove slack notification

- CHANGELOG.md
- README.md
* 6.8.15 as default version.
| [#1092](https://github.com/elastic/helm-charts/pull/1092) | [@jmlrt](https://github.com/jmlrt) | [6.8] [apm-server] Add  option loadBalancerIP to service (#1075)  |
| [#1080](https://github.com/elastic/helm-charts/pull/1080) | [@jmlrt](https://github.com/jmlrt) | [6.8] [meta] bump helm support to 3.5.2 (#1065)  |
| [#952](https://github.com/elastic/helm-charts/pull/952) | [@jmlrt](https://github.com/jmlrt) | [6.8] [meta] enable filebeat and metricbeat upgrade test  |
| [#1077](https://github.com/elastic/helm-charts/pull/1077) | [@jmlrt](https://github.com/jmlrt) | [6.8] [logstash] Add support to use pattern files (#883)  |
| [#1068](https://github.com/elastic/helm-charts/pull/1068) | …
> 6.8.15 release changelog

- CHANGELOG.md
- README.md
* 7.12.0 as default version.
| [#1093](https://github.com/elastic/helm-charts/pull/1093) | [@jmlrt](https://github.com/jmlrt) | [7.x] [apm-server] Add  option loadBalancerIP to service (#1075)  |
> 7.12.0 release changelog

- helpers/matrix.yml
- helpers/terraform/Makefile
This commit remove tests on GKE 1.15 and add tests on GKE 1.18 following
new GKE version updates:
https://cloud.google.com/kubernetes-engine/docs/release-notes#April_06_2021
> [meta] add tests for k8s 1.18 and remove 1.15

- helpers/matrix.yml
- helpers/terraform/Makefile
- [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
> [6.8] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)

- helpers/matrix.yml
- helpers/terraform/Makefile
- [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
> [7.x] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)

- helpers/matrix.yml
- helpers/terraform/Makefile
- [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
> [7.12] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)

- helpers/helm-tester/requirements.txt
- Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)
> [6.8] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)

- helpers/helm-tester/requirements.txt
- Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)
> [7.12] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)

- requirements.txt
- Bump py from 1.8.0 to 1.10.0 (#1155)
> [6.8] Bump py from 1.8.0 to 1.10.0 (#1155)

- requirements.txt
- Bump py from 1.8.0 to 1.10.0 (#1155)
> [7.12] Bump py from 1.8.0 to 1.10.0 (#1155)

- requirements.txt
- Bump py from 1.8.0 to 1.10.0 (#1155)
> [7.x] Bump py from 1.8.0 to 1.10.0 (#1155)

- CHANGELOG.md
- README.md
* 7.12.1 as default version.
| [#1173](https://github.com/elastic/helm-charts/pull/1173) | [@jmlrt](https://github.com/jmlrt) | [7.12] Bump py from 1.8.0 to 1.10.0 (#1155)  |
| [#1170](https://github.com/elastic/helm-charts/pull/1170) | [@jmlrt](https://github.com/jmlrt) | [7.12] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)  |
| [#1161](https://github.com/elastic/helm-charts/pull/1161) | [@jmlrt](https://github.com/jmlrt) | [7.12] [meta] add helm 3.5.3 support (#1128)  |
| [#1167](https://github.com/elastic/helm-charts/pull/1167) | [@jmlrt](https://github.com/jmlrt) | [7.12] [elasticsearch] Mark esMajorVersion as deprecated (#1109)  |
| [#1164](https://github.com/elastic/helm-charts/pull/1164) | [@jmlrt](https://github.com/jmlrt) …
> 7.12.1 release changelog

- logstash/templates/service.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
Backports the following commits to 6.8
[logstash] Add option loadBalancerIP to service (#1099)
> [6.8][logstash] Add option loadBalancerIP to service (#1099)

- elasticsearch/examples/upgrade/Makefile
- elasticsearch/examples/upgrade/test/goss.yaml
This commit fix the elasticsearch statefulset to rollout.
Also update the target version to the last released version
> [elasticsearch] fix statefulset to rollout in upgrade test

- .backportrc.json
- [meta] update backport config for 7.13 branch (#1198)
> [6.8] [meta] update backport config for 7.13 branch (#1198)

- CHANGELOG.md
- README.md
* 7.13.0 as default version.
| [#1205](https://github.com/elastic/helm-charts/pull/1205) | [@jmlrt](https://github.com/jmlrt) | [meta] update backport config for 7.13 branch (#1198)  |
| [#1197](https://github.com/elastic/helm-charts/pull/1197) | [@jmlrt](https://github.com/jmlrt) |  [meta] Initiate 7.13 branch  |
| [#1194](https://github.com/elastic/helm-charts/pull/1194) | [@jmlrt](https://github.com/jmlrt) | [meta] remove gke 1.16 tests (#1184)  |
| [#1175](https://github.com/elastic/helm-charts/pull/1175) | [@nittyy](https://github.com/nittyy) | [7.x][logstash] Add option loadBalancerIP to service (#1099)  |
| [#1174](https://github.com/elastic/helm-charts/pull/1174) | [@jmlrt](https://github.com/jmlrt) | [7.x] Bump py from 1.8.0 to 1.10.0 …
> 7.13.0 release changelog

- CHANGELOG.md
- README.md
* 6.8.16 as default version.
| [#1192](https://github.com/elastic/helm-charts/pull/1192) | [@jmlrt](https://github.com/jmlrt) | [meta] remove gke 1.16 tests (#1184)  |
| [#1176](https://github.com/elastic/helm-charts/pull/1176) | [@nittyy](https://github.com/nittyy) | [6.8][logstash] Add option loadBalancerIP to service (#1099)  |
| [#1172](https://github.com/elastic/helm-charts/pull/1172) | [@jmlrt](https://github.com/jmlrt) | [6.8] Bump py from 1.8.0 to 1.10.0 (#1155)  |
| [#1169](https://github.com/elastic/helm-charts/pull/1169) | [@jmlrt](https://github.com/jmlrt) | [6.8] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)  |
| [#1160](https://github.com/elastic/helm-charts/pull/1160) | [@jmlrt](https://github.com/jmlrt) | [6.8] …
> 6.8.16 release changelog

- elasticsearch/examples/networkpolicy/Makefile
- elasticsearch/examples/networkpolicy/values.yaml
- elasticsearch/templates/networkpolicy.yaml
- elasticsearch/tests/elasticsearch_test.py
- [elasticsearch] fix network policies http additional rules (#1111)
> [6.8] [elasticsearch] fix network policies http additional rules (#1111)

- elasticsearch/examples/networkpolicy/Makefile
- elasticsearch/examples/networkpolicy/values.yaml
- elasticsearch/templates/networkpolicy.yaml
- elasticsearch/tests/elasticsearch_test.py
- [elasticsearch] fix network policies http additional rules (#1111)
> [7.x] [elasticsearch] fix network policies http additional rules (#1111)

- elasticsearch/templates/statefulset.yaml
- elasticsearch/tests/elasticsearch_test.py
- elasticsearch/values.yaml
- [elasticsearch] only configure ES_JAVA_OPTS when value is set (#1089)
> [7.x] [elasticsearch] only configure ES_JAVA_OPTS when value is set (#1089)

- helpers/matrix.yml
This commit add tests on GKE 1.18 following new GKE version updates:
https://cloud.google.com/kubernetes-engine/docs/release-notes#May_19_2021
> [meta] add tests for k8s 1.19

- elasticsearch/examples/upgrade/Makefile
- [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
> [6.8] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)

- elasticsearch/examples/upgrade/Makefile
- [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
> [7.13] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)

- elasticsearch/examples/upgrade/Makefile
- [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
> [7.x] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)

- logstash/README.md
- logstash/templates/statefulset.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] feat: add podAffinity settings (#1257)
> [6.8] [logstash] feat: add podAffinity settings (#1257)

- CHANGELOG.md
- README.md
* 6.8.17 as default version.
| [#1278](https://github.com/elastic/helm-charts/pull/1278) | [@jmlrt](https://github.com/jmlrt) | [kibana] adding extra volumes and extra volume mounts (#557) (#1264)  |
| [#1275](https://github.com/elastic/helm-charts/pull/1275) | [@jmlrt](https://github.com/jmlrt) | [logstash] feat: add podAffinity settings (#1257)  |
| [#1272](https://github.com/elastic/helm-charts/pull/1272) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] Added health pod name override for compatability (#1058)  |
| [#1216](https://github.com/elastic/helm-charts/pull/1216) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] fix statefulset to rollout in upgrade test (#1189)  |
| [#1227](https://github.com/elastic/helm-charts/pull/1227) …
> 6.8.17 release changelog

- helpers/matrix.yml
This commit add tests on GKE 1.20 following new GKE version updates:
https://cloud.google.com/kubernetes-engine/docs/release-notes#June_25_2021
> [meta] add tests for k8s 1.20

- README.md
- [meta] update support matrix (#1305)
> [6.8] [meta] update support matrix (#1305)

- CHANGELOG.md
- README.md
* 6.8.18 as default version.
| [#1269](https://github.com/elastic/helm-charts/pull/1269) | [@jmlrt](https://github.com/jmlrt) | [6.8] [meta] add tests for k8s 1.19 (#1231)  |
| [#1306](https://github.com/elastic/helm-charts/pull/1306) | [@jmlrt](https://github.com/jmlrt) | [meta] update support matrix (#1305)  |
| [#1292](https://github.com/elastic/helm-charts/pull/1292) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 6.8.18-SNAPSHOT  |
> 6.8.18 release changelog

- README.md
This commit removes the existing support matrix and replace it by a
mention of the charts status (alpha, beta, ga) in the stack version
table. This change will avoid issue where the support matrix isn't
updated during a release.
Also remove the links to stack product docker image doc which are
already present in each chart specific README.
Also reorganize informations related to supported configuration under
this title and format line length.
> [meta] remove support matrix + nit doc changes

- README.md
- [meta] remove support matrix + nit doc changes (#1337)
> [6.8] [meta] remove support matrix + nit doc changes (#1337)

- helpers/matrix.yml
- [meta] add tests for k8s 1.20 (#1294)
> [6.8] [meta] add tests for k8s 1.20 (#1294)

- helpers/matrix.yml
Backports the following commits to 7.14:
- [meta] add tests for k8s 1.20 (#1294)
> [7.14] [meta] add tests for k8s 1.20 (#1294)

- elasticsearch/templates/NOTES.txt
Backports the following commits to 7.15:
- [elasticsearch] Add namespace to helm test command in NOTES.txt (#1105)
> [7.15] [elasticsearch] Add namespace to helm test command in NOTES.txt (#1105)

- elasticsearch/values.yaml
> [7.x] Fix typo (#1382)

- elasticsearch/values.yaml
Backports the following commits to 7.15:
- Fix typo (#1382)
> [7.15] Fix typo (#1382)

- helpers/matrix.yml
Backports the following commits to 7.15:
- [meta] add support for K8S 1.21 and remove 1.18 (#1410)
> [7.15] [meta] add support for K8S 1.21 and remove 1.18 (#1410)

- helpers/matrix.yml
- [meta] add support for K8S 1.21 and remove 1.18 (#1410)
> [6.8] [meta] add support for K8S 1.21 and remove 1.18 (#1410)

- metricbeat/README.md
- metricbeat/examples/default/test/goss-metrics.yaml
- metricbeat/examples/default/test/goss.yaml
- metricbeat/examples/oss/test/goss-metrics.yaml
- metricbeat/examples/oss/test/goss.yaml
- metricbeat/examples/oss/values.yaml
- metricbeat/examples/security/values.yaml
- metricbeat/examples/upgrade/values.yaml
- metricbeat/values.yaml
This commit updates metricbeat values to use the new Elasticsearch    
credentials from https://github.com/elastic/helm-charts/pull/1384.    
Relates to https://github.com/elastic/helm-charts/issues/1375
> [metricbeat] use new elasticsearch credentials

- elasticsearch/templates/statefulset.yaml
This commit set the readiness probe to use bash instead of sh. This is
required for Elasticsearch > 7.16.0 because the Docker image is now
based on Ubuntu instead of CentOS 8, and sh on Ubuntu isn't compatible
with the `if [[ ... -eq .... ]]` statements used in the readiness probe.
cc @elastic/es-delivery
> [elasticsearch] use bash for readiness script

- helpers/examples.mk
This commit update the way goss binary is retrieved in the
tests/examples. The goss binary is now downloaded locally then copied
inside the pod.
This is needed because the Elasticsearch Ubuntu based Docker images is
missing the ca-certificates package, and so the curl https command is
failling with `curl: (77) error setting certificate verify locations`
error.
Follow-up of https://github.com/elastic/helm-charts/pull/1458
Relates to https://github.com/elastic/helm-charts/pull/1459#issuecomment-989987927
> [meta] download goss outside of pods

- elasticsearch/templates/statefulset.yaml
- [elasticsearch] use bash for readiness script (#1458)
> [7.x] [elasticsearch] use bash for readiness script (#1458)

- helpers/examples.mk
- [meta] download goss outside of pods (#1460)
> [7.x] [meta] download goss outside of pods (#1460)

- elasticsearch/templates/statefulset.yaml
This commit is a follow up of 167278e2 and is updating the keystore
initContainer to also use bash instead of sh. This is required for
Elasticsearch > 7.16.0 because the Docker image is now based on Ubuntu
instead of CentOS 8, and sh on Ubuntu isn't compatible with the
`if [[... -eq ... ]]` statements.
> [elasticsearch] use bash for keystore init container

- elasticsearch/templates/statefulset.yaml
This commit fixes a typo in 4e31e0cf3d025f9ce877ac52d218f49d72e26447.
> [elasticsearch] fix a typo in 4e31e0cf3d025f9ce877ac52d218f49d72e26447

- elasticsearch/templates/statefulset.yaml
- [elasticsearch] use bash for keystore init container (#1464)
> [7.x] [elasticsearch] use bash for keystore init container (#1464)

- metricbeat/examples/oss/test/goss.yaml
- [metricbeat] remove es metricset search query for oss example (#1469)
> [7.x] [metricbeat] remove es metricset search query for oss example (#1469)

- .backportrc.json
This commits update sqren/backport config to handle 7.16 branch.
Also remove 7.14 and 7.15 branches.
> [meta] update backport config for 7.16 branch

- CHANGELOG.md
- README.md
* 6.8.21 as default version.
| [#1410](https://github.com/elastic/helm-charts/pull/1410) | [@jmlrt](https://github.com/jmlrt) | [meta] add support for K8S 1.21 and remove 1.18  |
| [#1300](https://github.com/elastic/helm-charts/pull/1300) | [@jonkerj](https://github.com/jonkerj) | [elasticsearch]: optionally disable SA token automount  |
| [#1382](https://github.com/elastic/helm-charts/pull/1382) | [@piglovesyou](https://github.com/piglovesyou) | Fix typo  |
| [#1386](https://github.com/elastic/helm-charts/pull/1386) | [@jmlrt](https://github.com/jmlrt) | [meta] fail make test on error  |
| [#1319](https://github.com/elastic/helm-charts/pull/1319) | [@cclausss](https://github.com/cclausss) | Fix typos discovered by codespell  |
| …
> 6.8.21 release changelog

- README.md
This commit fixes the links to access the latest documentation for
the 7.16.1 and 6.8.21 releases.
> [doc] Fix links to 6.8 and 7.16  documentation

- elasticsearch/examples/config/test/goss.yaml
- elasticsearch/examples/config/values.yaml
- elasticsearch/examples/security/test/goss.yaml
- elasticsearch/examples/security/values.yaml
- elasticsearch/templates/statefulset.yaml
This commit remove the usage of ELASTIC_USERNAME and replace it by
hardcoded "elastic" username.
This is required because ELASTIC_USERNAME don't seem to be supported
anymore supported by Elasticsearch (I couldn't find the exact version
where support was stopped).
This was already done as part of https://github.com/elastic/helm-charts/pull/1384 in the main branch.
> [elasticsearch] remove usage of ELASTIC_USERNAME

- elasticsearch/examples/config/test/goss.yaml
- elasticsearch/examples/config/values.yaml
- elasticsearch/examples/security/test/goss.yaml
- elasticsearch/examples/security/values.yaml
- elasticsearch/templates/statefulset.yaml
This commit remove the usage of ELASTIC_USERNAME and replace it by
hardcoded "elastic" username.
This is required because ELASTIC_USERNAME don't seem to be supported
anymore supported by Elasticsearch (I couldn't find the exact version
where support was stopped).
Backport of #1506
> [elasticsearch] remove usage of ELASTIC_USERNAME (#1506)

- CHANGELOG.md
- README.md
* 6.8.22 as default version.
| [#1508](https://github.com/elastic/helm-charts/pull/1508) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] remove usage of ELASTIC_USERNAME (#1506)  |
| [#1498](https://github.com/elastic/helm-charts/pull/1498) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 6.8.22-SNAPSHOT  |
> 6.8.22 release changelog

- helpers/helpers.py
According https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation , this fix python warnings when running tests.
Python 3.8
PyYaml 5.4
---
From PyYaml 6, Loader argument is required.
> [meta] fix yaml load warning in tests

- kibana/templates/deployment.yaml
This commit set the readiness probe to use bash instead of sh. This is
required for Kibana > 7.17.0 because the Docker image is now
based on Ubuntu instead of CentOS 8, and sh on Ubuntu isn't compatible
with the if [[ ... -eq .... ]] statements used in the readiness probe.
Fix #1529
> [kibana] use bash for readiness script

- kibana/templates/deployment.yaml
- [kibana] use bash for readiness script (#1530)
> [7.x] [kibana] use bash for readiness script (#1530)

- helpers/helpers.py
Backports the following commits to 7.16:
- [tests] fix yaml load warning (#1522)
> [7.16] [tests] fix yaml load warning (#1522)

- helpers/helpers.py
- [tests] fix yaml load warning (#1522)
> [6.8] [tests] fix yaml load warning (#1522)

- .backportrc.json
7.x branch has been removed has there won't be any 7.18 minor version.
> [meta] remove 7.x branch from backport config

- .backportrc.json
- [meta] remove 7.x branch from backport config (#1556)
> [7.17] [meta] remove 7.x branch from backport config (#1556)

- .backportrc.json
- [meta] remove 7.x branch from backport config (#1556)
> [6.8] [meta] remove 7.x branch from backport config (#1556)

- elasticsearch/templates/poddisruptionbudget.yaml
- elasticsearch/templates/service.yaml
- elasticsearch/templates/test/test-elasticsearch-health.yaml
The chomp "{{-" removes newline also - so we end up with a resource yaml which looks like:
```
---kind: Service
apiVersion: v1
...
```
This causes errors in ArgoCD: "error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in ..."
Fix #1418
> [elasticsearch] Move the yaml separator inside the condition

- elasticsearch/templates/poddisruptionbudget.yaml
- elasticsearch/templates/service.yaml
- elasticsearch/templates/test/test-elasticsearch-health.yaml
- [elasticsearch] Move the yaml separator inside the condition (#1538)
> [6.8] [elasticsearch] Move the yaml separator inside the condition (#1538)

- elasticsearch/templates/poddisruptionbudget.yaml
- elasticsearch/templates/service.yaml
- elasticsearch/templates/test/test-elasticsearch-health.yaml
- [elasticsearch] Move the yaml separator inside the condition (#1538)
> [7.17] [elasticsearch] Move the yaml separator inside the condition (#1538)

- apm-server/templates/deployment.yaml
- apm-server/tests/apmserver_test.py
pod labels were missing from APM template.
> [apm-server] fix podLabels

- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/rolebinding.yaml
- elasticsearch/templates/serviceaccount.yaml
- elasticsearch/templates/statefulset.yaml
This commit refactor the way we define the ServiceAccount name to fix an
issue where a ServiceAccount is created with a custom name but the
Statefulset is trying to use a different ServiceAccount.
Fix #1455
> [elasticsearch] fix ServiceAccount inconsistencies

- apm-server/templates/deployment.yaml
- fix(APM): add pod labels (#1527)
> [7.17] fix(APM): add pod labels (#1527)

- apm-server/tests/apmserver_test.py
> [7.17] [APM] fix podLabels (#1521)

- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/rolebinding.yaml
- elasticsearch/templates/serviceaccount.yaml
- elasticsearch/templates/statefulset.yaml
- [elasticsearch] fix ServiceAccount inconsistencies (#1580)
> [7.17] [elasticsearch] fix ServiceAccount inconsistencies (#1580)

- logstash/templates/_helpers.tpl
- logstash/templates/rolebinding.yaml
- logstash/templates/serviceaccount.yaml
- logstash/templates/statefulset.yaml
- [logstash] fix ServiceAccount inconsistencies (#1581)
> [7.17] [logstash] fix ServiceAccount inconsistencies (#1581)

- helpers/helm-tester/Dockerfile
- metricbeat/README.md
- metricbeat/examples/default/Makefile
- metricbeat/examples/oss/Makefile
- metricbeat/examples/security/Makefile
- metricbeat/examples/upgrade/Makefile
- metricbeat/requirements.lock
- metricbeat/requirements.yaml
- [metricbeat] bump kube-state-metrics to version 4.7.0 (#1524)
> [7.17] [metricbeat] bump kube-state-metrics to version 4.7.0 (#1524)

- logstash/templates/service.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] add externalTrafficPolicy support (#1570)
> [7.17] [logstash] add externalTrafficPolicy support (#1570)

- logstash/templates/ingress.yaml
- logstash/tests/logstash_test.py
- logstash/values.yaml
- [logstash] add flexible ingress (#1569)
> [7.17] [logstash] add flexible ingress (#1569)

- filebeat/templates/role.yaml
- metricbeat/templates/role.yaml
- metricbeat/values.yaml
- [metricbeat] Adding custerRole permissions for leader election (#1422)
> [7.17] [metricbeat] Adding custerRole permissions for leader election (#1422)

- filebeat/templates/rolebinding.yaml
- filebeat/values.yaml
This commits add a rolebinding and cluster role rules to match
https://github.com/elastic/beats/blob/main/deploy/kubernetes/filebeat-kubernetes.yaml
Follow-up of #1422
> [filebeat] add missing rolebinding and cluster role rules

- elasticsearch/templates/statefulset.yaml
- [elasticsearch] add keystore container securityContext (#1494)
> [7.17] [elasticsearch] add keystore container securityContext (#1494)

- metricbeat/templates/rolebinding.yaml
- metricbeat/values.yaml
- [metricbeat] add missing rolebinding and cluster role rules (#1603)
> [7.17] [metricbeat] add missing rolebinding and cluster role rules (#1603)

- filebeat/templates/rolebinding.yaml
- filebeat/values.yaml
- [filebeat] add missing rolebing and cluster role rules (#1602)
> [7.17] [filebeat] add missing rolebing and cluster role rules (#1602)

- metricbeat/examples/upgrade/Makefile
This commit fix the Metricbeat upgrade test by bumping the source
version to 7.17.1. This is required because
https://github.com/elastic/helm-charts/pull/1524 introduced a new
kube-state-metrics version that prevent upgrade from previous versions.
> [metricbeat] fix upgrade test

- metricbeat/examples/upgrade/Makefile
- [metricbeat] fix upgrade test (#1612)
> [7.17] [metricbeat] fix upgrade test (#1612)

- elasticsearch/templates/_helpers.tpl
Fix the cname and alternatives names of the certificate generated by Elasticsearch chart to match the Elasticsearch service name.
> [elasticsearch] fix certificate cnames

- elasticsearch/examples/upgrade/Makefile
This commit update the upgrade test to upgrade Elasticsearch chart from
7.17.1 to 8.x instead of from 7.4.0.
This is because Elasticsearch requires upgrading to the last minor 7.x
version (7.17.x) before proceding to 8.x major upgrade.
> [elasticsearch] upgrade test from 7.17.1 to 8.x

- apm-server/examples/upgrade/Makefile
- filebeat/examples/upgrade/Makefile
This commit updates the upgrade tests for apm-server and filebeat
to use 7.10.0 base version before trying an upgrade.
This is required because the previous versions used
`rbac.authorization.k8s.io/v1beta1` K8S API which isn't supported
anymore in K8S 1.22.
> [meta] update upgrade tests base version

- apm-server/examples/upgrade/Makefile
- filebeat/examples/upgrade/Makefile
- [meta] update upgrade tests base version (#1631)
> [7.17] [meta] update upgrade tests base version (#1631)

- helpers/matrix.yml
- Remove GKE 1.19 support
- Add GKE 1.23 and 1.24 support
Relates to https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule_for_static_no_channel_versions
> [meta] update supported gke versions

- elasticsearch/templates/secret-cert.yaml
This commit remove the `pre-upgrade` hook for the certificate secret to
ensure that the certificate isn't regenerate each time we run the
`helm upgrade` command.
> [elasticsearch] do not regenerate certs during upgrade

- elasticsearch/templates/test/test-elasticsearch-health.yaml
This commit fix the Elasticsearch Helm test by adding security
compatibility.
> [elasticsearch] fix helm test

- .ci/jobs/elastic+helm-charts+main+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+main+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+main+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+main+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+main+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+main+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+main+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+main+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+main+template-lint-python.yml
- .ci/jobs/elastic+helm-charts+main+template-testing.yml
- .ci/jobs/elastic+helm-charts+pull-request+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+pull-request+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+pull-request+integration-metricbeat.yml
- .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml
- .ci/jobs/elastic+helm-charts+pull-request+template-testing.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
- .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
- .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
- .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
- .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
- .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
- .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
- .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
This commit is updating the helm-charts Jenkins jobs configuration to
use Ubuntu nodes only. This change is mostly to fix a bug with the ampersands
(`&`) in the node labels.
The only real change here is replacing every occurrence of `docker&&virtual`
by `ubuntu`. All other changes are simply yaml formatting done by VS Code.
> [meta] set jenkins workers to ubuntu

- elasticsearch/templates/_helpers.tpl
- elasticsearch/templates/secret-cert.yaml
This commit update the way we generate the Elasticsearch certs to lookup
if the certs secret already exists and reuse the secrets instead of regenerate
the certs.
This fix the issue when upgrading from a previous version of the chart
that doesn't include the certs secret by ensuring that the certs secret
is created if it doesn't exists.
This method also add more flexibility than charts hooks by ensuring that
the certs won't be rotated each time we upgrade the chart.
Found in https://stackoverflow.com/a/61715870
> [elasticsearch] do not regenerate certs when they already exists

- elasticsearch/templates/statefulset.yaml
This commit fix the node.roles variable for client role with
Elasticsearch version > 8.3.0.
As client nodes are nodes that don't have any other roles,
setting the client roles is done by configuring `node.roles: []`
(empty list).
Elasticsearch chart usually define `node.roles` as an environment
variable, however, for client nodes, setting an empty list as value of
an environment variable isn't recognized by Elasticsearch so we were
required to also add it to the `elasticsearch.yaml` config file (more
details in
https://github.com/elastic/helm-charts/pull/1186#discussion_r631225687).
Starting with Elasticsearch 8.3.0 this is not working anymore and
Elasticsearch fails to start is a `node.roles` environment variable is
defined with an empty list as value.
This commit define the `node.roles` …
> [elasticsearch] fix node roles for clients nodes

- kibana/examples/upgrade/Makefile
- kibana/examples/upgrade/test/goss.yaml
- kibana/examples/upgrade/values.yaml
- kibana/templates/job.yaml
Fix the kibana upgrade test by installing Elasticsearch and Kibana 7.17.1 first, before upgrading them to 8.4.1 (because Kibana 7.17.1 can't connect to Elasticsearch 8.4.1).
Also fix the post-delete hook that was deleting kibana token during the upgrade, making impossible for the new kibana pod to connect to Elasticsearch.
> [kibana] update the upgrade test

- filebeat/examples/default/test/goss.yaml
- filebeat/examples/deployment/values.yaml
- filebeat/examples/oss/values.yaml
- filebeat/examples/security/values.yaml
- filebeat/examples/upgrade/values.yaml
- metricbeat/examples/default/test/goss-metrics.yaml
- metricbeat/examples/default/test/goss.yaml
- metricbeat/examples/oss/values.yaml
- metricbeat/examples/security/values.yaml
- metricbeat/examples/upgrade/values.yaml
This commit increase the memory limit for Filebeat and Metricbeat goss
tests. This should help with the regular `Error 137` during goss tests.
Indeed `Error 137` seems to be related to OOM. As beats pods default
memory limit is really small (200Mb), it seems that injecting goss
inside the pods to run the test can reach the memory limit regularly.
Also remove the biggest test in the default config test examples to make
goss use less memory because we can't override default values for these
tests.
> [filebeat][metricbeat] increase memory limit for goss tests

- elasticsearch/templates/podsecuritypolicy.yaml
- logstash/templates/podsecuritypolicy.yaml
- Fix PodSecurityPolicy error in v1.22 (#1661)
> [7.17] Fix PodSecurityPolicy error in v1.22 (#1661)

- kibana/examples/upgrade/Makefile
- kibana/templates/NOTES.txt
- kibana/templates/configmap-helm-scripts.yaml
- kibana/templates/deployment.yaml
- kibana/templates/post-delete-job.yaml
- kibana/templates/post-delete-role.yaml
- kibana/templates/post-delete-rolebinding.yaml
- kibana/templates/post-delete-serviceaccount.yaml
- kibana/templates/pre-install-job.yaml
- kibana/templates/pre-install-role.yaml
- kibana/templates/pre-install-rolebinding.yaml
- kibana/templates/pre-install-serviceaccount.yaml
This PR moves the Elasticsearch token for Kibana creation into Helm pre-install hooks and adds it to a K8S secret so it can be used by every pod of the Kibana Deployment.
The K8S secret and all linked resources are cleaned in post-delete hooks.
The call to Elasticsearch and K8S API to create the ES token and convert it to a secret are done in a Node JS script because the only language runtime available in the Kibana Docker image are Node and Bash, but `jq` command isn't available which exclude Bash script.
The Node JS script is also available in plain JS format to facilitate the review: https://gist.github.com/jmlrt/482b3d984588c1d3e10a84ce5fcd7b3b
Many thanks @pugnascotia for the help on this script 🙏🏻 
Follow-up of https://github.com/elastic/helm-charts/pull/1679
Replace …
> [kibana] create a secret with es token

- README.md
This commit adds more details about when it is good to override the `imageTag` value to use the latest chart version with Docker images from the latest stack version.
Relates to https://github.com/elastic/helm-charts/issues/1710#issuecomment-1313247262
> [meta] overriding imageTag recommendation

- README.md
- [meta] overriding imageTag recommendation (#1723)
> [7.17] [meta] overriding imageTag recommendation (#1723)
