elastic/helm-charts

elasticsearch/README.md, elasticsearch/examples/docker-for-mac/Makefile, elasticsearch/examples/docker-for-mac/values.yaml, helpers/matrix.yml
Closes: https://github.com/elastic/helm-charts/issues/18
=> Add documentation and example for running the chart on docker-for-mac

elasticsearch/Chart.yaml, kibana/Chart.yaml
Added icon line to Chart.yaml files to display logo in Helm hub.
=> Added icons to ES and Kibana Chart.yaml

kibana/tests/kibana_test.py
Adding tests for pull request: #38
=> Add test coverage for serviceAccount and podSecurityContext

helpers/terraform/Dockerfile
Add some `curl` retries since some CI builds encountered issues doing
these downloads.
=> Add retries to curl commands in Dockerfile

elasticsearch/examples/7.1.x/Makefile, elasticsearch/examples/7.1.x/test/goss.yaml, elasticsearch/examples/7.1.x/values.yaml, helpers/matrix.yml, kibana/examples/7.1.x/Makefile, kibana/examples/7.1.x/test/goss.yaml, kibana/examples/7.1.x/values.yml
Add tests for `7.1.x` for testing `7.x` branch development.
=> Add 7.1.0 snapshot testing

elasticsearch/values.yaml, helpers/common.mk, kibana/values.yaml
To make sure we catch linting errors as seen in #59
=> Enable strict mode for helm lint test

elasticsearch/examples/7.0.x/test/goss.yaml, elasticsearch/examples/7.0.x/values.yaml, kibana/examples/7.0.x/test/goss.yaml, kibana/examples/7.0.x/values.yml
7.0.0 was released yesterday, let's try it out.
=> Update examples to 7.0.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, CHANGELOG.md, elasticsearch/Chart.yaml, elasticsearch/README.md, elasticsearch/examples/default/test/goss.yaml, elasticsearch/values.yaml, helpers/bumper.py, kibana/Chart.yaml, kibana/README.md, kibana/examples/default/test/goss.yaml, kibana/values.yaml
The `about:` sections needed to be added to the issue templates otherwise they don't show up :(
=> Release 7.0.1 and update the changelog

.ci/views/views.yml
=> [ci] add jenkins view for helm charts jobs

.ci/views/views.yml
fix https://github.com/elastic/helm-charts/pull/276
=> [ci] fix jjb view regex

kibana/README.md, kibana/templates/_helpers.tpl, kibana/templates/ingress.yaml
I don't know if it's possible to add template tests for these changes as they are affected by Values...
=> [kibana] Add compatibility for k8s 1.16

filebeat/README.md
=> [filebeat] change min k8s version due to daemonset apiVersion

elasticsearch/README.md
related to https://github.com/elastic/helm-charts/pull/333/files#r335988708
=> [elasticsearch] fix deprecated note

elasticsearch/templates/statefulset.yaml, elasticsearch/tests/elasticsearch_test.py
=> use same imagePullPolicy in initContainer

elasticsearch/templates/statefulset.yaml, elasticsearch/tests/elasticsearch_test.py
=> [elasticsearch] Apply labels to all pods

apm-server/Chart.yaml, apm-server/README.md, apm-server/examples/6.x/test/goss.yaml, apm-server/examples/default/test/goss.yaml, apm-server/examples/oss/test/goss.yaml, apm-server/examples/oss/values.yaml, apm-server/examples/security/test/goss.yaml, apm-server/values.yaml
=> [apm-server] bump to 7.5.2

apm-server/templates/ingress.yaml
=> Fix template name

apm-server/templates/hpa.yaml
=> fix apiVersion of HPA

.ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml, .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml
This PR should fix CI jobs on 7.7 branch (example: [elastic+helm-charts+7.7+cluster-creation](https://devops-ci.elastic.co/job/elastic+helm-charts+7.7+cluster-creation/KUBERNETES_VERSION=1.14,label=docker&&virtual/3/console)).
Related to #541
=> [meta] fix ci jobs

BREAKING_CHANGES.md, CHANGELOG.md
=> [meta] update changelog and breaking changes for 6.8.9

elasticsearch/examples/multi/README.md
This is a very simple PR that fixed some broken links so I've omitted the checklist.
=> Fix values links in examples/multi/README.md

apm-server/values.yaml
=> [apm-server] increase memory limit

BREAKING_CHANGES.md, CHANGELOG.md
=> [meta] update changelog for 7.8.0 release

logstash/examples/security/test/goss.yaml
This commit fixes the expected version in security goss test.
=> [logstash] fix version in security test

kibana/README.md, logstash/README.md
=> [doc] fix copy-paste errors

filebeat/templates/clusterrole.yaml
=> [filebeat] add permission to list nodes

elasticsearch/templates/test/test-elasticsearch-health.yaml
Fix https://github.com/elastic/helm-charts/issues/701
=> [elasticsearch] Update test image pull policy.

apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
- Update oss docker image links to new Elastic registry
- Fix some other links
=> [doc] fix some links

.ci/jobs/elastic+helm-charts+staging.yml
This commit fix an indentation issue in #718
=> fixup! [meta] add slack notifications to CI jobs (#718)

CONTRIBUTING.md
This commit fixes a few typo in our contributing doc.
=> [doc] fix typos

elasticsearch/README.md, elasticsearch/examples/migration/README.md, filebeat/README.md
This PR update the links to Elastic doc site
=> [doc] update doc links

BREAKING_CHANGES.md, CHANGELOG.md, README.md, apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
This PR update the changelog following https://github.com/elastic/helm-charts/pull/787 & https://github.com/elastic/helm-charts/pull/788
=> [meta] Update change log for 6.8.12 / 7.9.0 releases

logstash/templates/service-headless.yaml, logstash/tests/logstash_test.py
=> [logstash] Fix headless service ports spec

CHANGELOG.md, README.md
This PR update the changelog following #803
=> [meta] update changelog for 7.9.1 release

README.md, apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
README instructions were misleading.
=> Specify chart version in install instructions

apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
=> [all] Remove development warnings for 7.9.3 release

apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
=> Update warning on charts readme

apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
Relates to https://github.com/elastic/helm-charts/pull/884
=> Add warning comment placeholder (7.x branch)

apm-server/README.md, elasticsearch/README.md, filebeat/README.md, kibana/README.md, logstash/README.md, metricbeat/README.md
Relates to https://github.com/elastic/helm-charts/pull/884
=> Add warning comment placeholder (6.8 branch)

.ci/jobs/elastic+helm-charts+pull-request+cluster-cleanup.yml, .ci/jobs/elastic+helm-charts+pull-request+cluster-creation.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-apm-server.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-elasticsearch.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-filebeat.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-kibana.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-logstash.yml, .ci/jobs/elastic+helm-charts+pull-request+integration-metricbeat.yml, .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml, .ci/jobs/elastic+helm-charts+pull-request+template-testing.yml
This commit update PR jobs to allow concurrency. Only the multijob
allowed concurrency but not the downstream jobs
=> [meta] allows concurrent jobs for pr

.backportrc.json
This commit add the config file to manage backport PR using
https://github.com/sqren/backport
=> [meta] add config for backport

apm-server/README.md, apm-server/templates/deployment.yaml, apm-server/tests/apmserver_test.py, apm-server/values.yaml, elasticsearch/README.md, elasticsearch/templates/statefulset.yaml, elasticsearch/tests/elasticsearch_test.py, elasticsearch/values.yaml, filebeat/README.md, filebeat/templates/daemonset.yaml, filebeat/tests/filebeat_test.py, filebeat/values.yaml, kibana/README.md, kibana/templates/deployment.yaml, kibana/tests/kibana_test.py, kibana/values.yaml, logstash/README.md, logstash/templates/statefulset.yaml, logstash/tests/logstash_test.py, logstash/values.yaml, metricbeat/README.md, metricbeat/templates/daemonset.yaml, metricbeat/templates/deployment.yaml, metricbeat/tests/metricbeat_test.py, metricbeat/values.yaml
- [all] add hostaliases (#970)
=> [6.8] [all] add hostaliases (#970)

apm-server/README.md, apm-server/templates/deployment.yaml, apm-server/tests/apmserver_test.py, apm-server/values.yaml, elasticsearch/README.md, elasticsearch/templates/statefulset.yaml, elasticsearch/tests/elasticsearch_test.py, elasticsearch/values.yaml, filebeat/README.md, filebeat/templates/daemonset.yaml, filebeat/tests/filebeat_test.py, filebeat/values.yaml, kibana/README.md, kibana/templates/deployment.yaml, kibana/tests/kibana_test.py, kibana/values.yaml, logstash/README.md, logstash/templates/statefulset.yaml, logstash/tests/logstash_test.py, logstash/values.yaml, metricbeat/README.md, metricbeat/templates/daemonset.yaml, metricbeat/templates/deployment.yaml, metricbeat/tests/metricbeat_test.py, metricbeat/values.yaml
- [all] add hostaliases (#970)
=> [7.x] [all] add hostaliases (#970)

filebeat/README.md, filebeat/templates/clusterrole.yaml, filebeat/values.yaml
Co-authored-by: Julien Mailleret <8582351+jmlrt@users.noreply.github.com>
=> [filebeat] Configurable ClusterRole (#978)

filebeat/README.md, metricbeat/README.md
Co-authored-by: ksorensen@scramsystems.com <ksorensen@scramsystems.com>
=> [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled. (#997)

CHANGELOG.md
=> 7.10.2 changelog

BREAKING_CHANGES.md, CHANGELOG.md, README.md
* 7.11.1 as default version.
| PR                                                        | Author                                                   | Title                                                                                                                        |
|-----------------------------------------------------------|----------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| [#1053](https://github.com/elastic/helm-charts/pull/1053) | [@jmlrt](https://github.com/jmlrt)                       | [elasticsearch][kibana] remove oss examples (#1046)                                                                          |
| …
=> 7.11.1 changelog

CHANGELOG.md, README.md
* 7.11.2 as default version.
| [#1081](https://github.com/elastic/helm-charts/pull/1081) | [@jmlrt](https://github.com/jmlrt) | [7.11] [meta] bump helm support to 3.5.2 (#1065)  |
| [#1078](https://github.com/elastic/helm-charts/pull/1078) | [@jmlrt](https://github.com/jmlrt) | [7.11] [logstash] Add support to use pattern files (#883)  |
| [#1072](https://github.com/elastic/helm-charts/pull/1072) | [@elasticmachine](https://github.com/elasticmachine) | Bump 7.11 branch to 7.11.2-SNAPSHOT  |
=> 7.11.2 release changelog

helpers/helm-tester/requirements.txt, requirements.txt
- [meta] update PyYAML dependencies (#1140)
=> [6.8] [meta] update PyYAML dependencies (#1140)

helpers/helm-tester/requirements.txt, requirements.txt
- [meta] update PyYAML dependencies (#1140)
=> [7.12] [meta] update PyYAML dependencies (#1140)

helpers/helm-tester/requirements.txt, requirements.txt
- [meta] update PyYAML dependencies (#1140)
=> [7.x] [meta] update PyYAML dependencies (#1140)

.backportrc.json
- [meta] update backport config for 7.12 branch (#1112)
=> [6.8] [meta] update backport config for 7.12 branch (#1112)

.backportrc.json
- [meta] update backport config for 7.12 branch (#1112)
=> [7.12] [meta] update backport config for 7.12 branch (#1112)

.backportrc.json
- [meta] update backport config for 7.12 branch (#1112)
=> [7.x] [meta] update backport config for 7.12 branch (#1112)

.backportrc.json
This commits update sqren/backport config to handle 7.13 branch.
Also remove 7.12 branch.
=> [meta] update backport config for 7.13 branch

.backportrc.json
- [meta] update backport config for 7.13 branch (#1198)
=> [7.13] [meta] update backport config for 7.13 branch (#1198)

.backportrc.json
- [meta] update backport config for 7.13 branch (#1198)
=> [7.x] [meta] update backport config for 7.13 branch (#1198)

CHANGELOG.md, README.md
Reverts elastic/helm-charts#1223
=> Revert "7.13.0 release changelog"

CHANGELOG.md, README.md, elasticsearch/examples/upgrade/Makefile, elasticsearch/examples/upgrade/test/goss.yaml
Also update elasticsearch upgrade test with 7.13.0
=> 7.13.0 changelog

elasticsearch/examples/networkpolicy/Makefile, elasticsearch/examples/networkpolicy/values.yaml, elasticsearch/templates/networkpolicy.yaml, elasticsearch/tests/elasticsearch_test.py
- [elasticsearch] fix network policies http additional rules (#1111)
=> [7.13] [elasticsearch] fix network policies http additional rules (#1111)

CHANGELOG.md, README.md
* 7.13.1 as default version.
| [#1211](https://github.com/elastic/helm-charts/pull/1211) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] only configure ES_JAVA_OPTS when value is set (#1089)  |
| [#1208](https://github.com/elastic/helm-charts/pull/1208) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] fix network policies http additional rules (#1111)  |
| [#1228](https://github.com/elastic/helm-charts/pull/1228) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 7.13.1-SNAPSHOT  |
=> 7.13.1 release changelog

CHANGELOG.md, README.md
* 7.13.2 as default version.
| [#1220](https://github.com/elastic/helm-charts/pull/1220) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] remove unused sidecarResources value (#1185)  |
| [#1217](https://github.com/elastic/helm-charts/pull/1217) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] fix statefulset to rollout in upgrade test (#1189)  |
| [#1214](https://github.com/elastic/helm-charts/pull/1214) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] remove masterTerminationFix (#1183)  |
| [#1238](https://github.com/elastic/helm-charts/pull/1238) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 7.13.2-SNAPSHOT  |
=> 7.13.2 release changelog

logstash/README.md, logstash/templates/statefulset.yaml, logstash/tests/logstash_test.py, logstash/values.yaml
=> [logstash] feat: add podAffinity settings

helpers/matrix.yml
- [meta] add tests for k8s 1.19 (#1231)
=> [7.13] [meta] add tests for k8s 1.19 (#1231)

helpers/matrix.yml
- [meta] add tests for k8s 1.19 (#1231)
=> [7.x] [meta] add tests for k8s 1.19 (#1231)

logstash/README.md, logstash/templates/statefulset.yaml, logstash/tests/logstash_test.py, logstash/values.yaml
- [logstash] feat: add podAffinity settings (#1257)
=> [7.x] [logstash] feat: add podAffinity settings (#1257)

logstash/README.md, logstash/templates/statefulset.yaml, logstash/tests/logstash_test.py, logstash/values.yaml
- [logstash] feat: add podAffinity settings (#1257)
=> [7.13] [logstash] feat: add podAffinity settings (#1257)

CHANGELOG.md, README.md
* 7.13.3 as default version.
| [#1288](https://github.com/elastic/helm-charts/pull/1288) | [@jmlrt](https://github.com/jmlrt) | [meta] remove gke 1.17 tests (#1286)  |
| [#1279](https://github.com/elastic/helm-charts/pull/1279) | [@jmlrt](https://github.com/jmlrt) | [kibana] adding extra volumes and extra volume mounts (#557) (#1264)  |
| [#1276](https://github.com/elastic/helm-charts/pull/1276) | [@jmlrt](https://github.com/jmlrt) | [logstash] feat: add podAffinity settings (#1257)  |
| [#1273](https://github.com/elastic/helm-charts/pull/1273) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] Added health pod name override for compatability (#1058)  |
| [#1270](https://github.com/elastic/helm-charts/pull/1270) | …
=> 7.13.3 release changelog

CHANGELOG.md, README.md
* 7.13.4 as default version.
| [#1293](https://github.com/elastic/helm-charts/pull/1293) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 7.13.4-SNAPSHOT  |
=> 7.13.4 release changelog

README.md
This commit update the support matrix for releases > 7.11.
=> [meta] update support matrix

README.md
- [meta] update support matrix (#1305)
=> [7.13] [meta] update support matrix (#1305)

README.md
- [meta] update support matrix (#1305)
=> [7.x] [meta] update support matrix (#1305)

CHANGELOG.md, README.md
=> 7.14.0 release changelog

README.md
- [meta] remove support matrix + nit doc changes (#1337)
=> [7.x] [meta] remove support matrix + nit doc changes (#1337)

README.md
Backports the following commits to 7.14:
- [meta] remove support matrix + nit doc changes (#1337)
=> [7.14] [meta] remove support matrix + nit doc changes (#1337)

helpers/matrix.yml
- [meta] add tests for k8s 1.20 (#1294)
=> [7.x] [meta] add tests for k8s 1.20 (#1294)

helpers/matrix.yml
Backports the following commits to 7.15:
- [meta] add tests for k8s 1.20 (#1294)
=> [7.15] [meta] add tests for k8s 1.20 (#1294)

CHANGELOG.md, README.md
* 7.15.0 as default version.
| [#1294](https://github.com/elastic/helm-charts/pull/1294) | [@jmlrt](https://github.com/jmlrt) | [meta] add tests for k8s 1.20  |
| [#1232](https://github.com/elastic/helm-charts/pull/1232) | [@jmlrt](https://github.com/jmlrt) | [meta] add helm 3.6.2 support |
| [#1116](https://github.com/elastic/helm-charts/pull/1116) | [@nflaig](https://github.com/nflaig) | [elasticsearch] add value to disable tests  |
| [#1115](https://github.com/elastic/helm-charts/pull/1115) | [@nflaig](https://github.com/nflaig) | [elasticsearch] add value to disable service |
| [#1105](https://github.com/elastic/helm-charts/pull/1105) | [@moritazy](https://github.com/moritazy) | [elasticsearch] Add namespace to helm test command in NOTES.txt …
=> 7.15.0 release changelog

.backportrc.json
Backports the following commits to 7.16:
- [meta] update backport config for 7.16 branch (#1476)
=> [7.16] [meta] update backport config for 7.16 branch (#1476)

elasticsearch/values.yaml
=> [elasticsearch] fix a lines order in example values

apm-server/templates/ingress.yaml, apm-server/values.yaml, elasticsearch/templates/ingress.yaml, elasticsearch/tests/elasticsearch_test.py, elasticsearch/values.yaml, kibana/templates/ingress.yaml, kibana/tests/kibana_test.py, kibana/values.yaml, logstash/templates/ingress.yaml, logstash/tests/logstash_test.py, logstash/values.yaml
Backports the following commits to 7.16:
- [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)
=> [7.16] [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)

apm-server/templates/ingress.yaml, apm-server/values.yaml, elasticsearch/templates/ingress.yaml, elasticsearch/tests/elasticsearch_test.py, elasticsearch/values.yaml, kibana/templates/ingress.yaml, kibana/tests/kibana_test.py, kibana/values.yaml, logstash/templates/ingress.yaml, logstash/tests/logstash_test.py, logstash/values.yaml
- [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)
=> [7.x] [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)

CHANGELOG.md, README.md
* 7.16.2 as default version.
| [#1507](https://github.com/elastic/helm-charts/pull/1507) | [@jmlrt](https://github.com/jmlrt) | [elasticsearch] remove usage of ELASTIC_USERNAME (#1506)  |
| [#1499](https://github.com/elastic/helm-charts/pull/1499) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 7.16.2-SNAPSHOT  |
=> 7.16.2 release changelog

helpers/helpers.py
- [tests] fix yaml load warning (#1522)
=> [7.x] [tests] fix yaml load warning (#1522)

CHANGELOG.md, README.md
* 7.16.3 as default version.
| [#1533](https://github.com/elastic/helm-charts/pull/1533) | [@ebuildy](https://github.com/ebuildy) | [tests] fix yaml load warning (#1522)  |
| [#1517](https://github.com/elastic/helm-charts/pull/1517) | [@elasticmachine](https://github.com/elasticmachine) | Bump version to 7.16.3-SNAPSHOT  |
| [#1502](https://github.com/elastic/helm-charts/pull/1502) | [@ebuildy](https://github.com/ebuildy) | [elasticsearch] #1495 Configure JVM options files (#1496)  |
=> 7.16.3 release changelog

.backportrc.json
This commits update sqren/backport config to handle 7.17 branch.
Also remove 7.16 branch.
=> [meta] update backport config for 7.17 branch

.backportrc.json
- [meta] update backport config for 7.17 branch (#1555)
=> [7.17] [meta] update backport config for 7.17 branch (#1555)

.backportrc.json
- [meta] update backport config for 7.17 branch (#1555)
=> [6.8] [meta] update backport config for 7.17 branch (#1555)

apm-server/templates/deployment.yaml
=> fix(APM): add pod labels

elasticsearch/templates/poddisruptionbudget.yaml, elasticsearch/templates/podsecuritypolicy.yaml, logstash/templates/poddisruptionbudget.yaml, logstash/templates/podsecuritypolicy.yaml
- Add support to PodDisruptionBudget policy/v1 (#1420)
=> [7.17] [elasticsearch][logstash] Add support to PodDisruptionBudget policy/v1 (#1420)

.ci/jobs.t/elastic+helm-charts+{branch}+template-testing.yml, elasticsearch/tests/elasticsearch_test.py, filebeat/tests/filebeat_test.py, helpers/common.mk, helpers/helm-tester/Dockerfile, helpers/helm-tester/requirements.txt, helpers/terraform/Dockerfile, logstash/tests/logstash_test.py, metricbeat/tests/metricbeat_test.py, requirements.txt
- [meta] update docker images (#1604)
=> [7.17] [meta] update docker images (#1604)

CHANGELOG.md, README.md
* 7.17.3 as default version.
| PR                                                        | Author                             | Title                                    |
|-----------------------------------------------------------|------------------------------------|------------------------------------------|
| [#1632](https://github.com/elastic/helm-charts/pull/1632) | [@jmlrt](https://github.com/jmlrt) | [meta] update upgrade tests base version |
| [#1622](https://github.com/elastic/helm-charts/pull/1622) | [@jmlrt](https://github.com/jmlrt) | [metricbeat] fix upgrade test            |
Relates to #1649
=> 7.17.3 release changelog

helpers/matrix.yml
- [meta] update supported gke versions (#1673)
=> [7.17] [meta] update supported gke versions (#1673)

.ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml, .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml, .ci/jobs.t/elastic+helm-charts+{branch}+template-lint-python.yml, .ci/jobs.t/elastic+helm-charts+{branch}+template-testing.yml
- [meta] set jenkins workers to ubuntu (#1690)
=> [7.17] [meta] set jenkins workers to ubuntu (#1690)

.ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml
=> [meta] fix yaml indent

.ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml, .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml, .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml
=> [meta] follow-up of #1698
